// Generated from kernels.metal by scripts/embed-metal.py — do not edit.
static const char *k_metal_src =
    "// Metal compute kernels: the full single-token forward pass.\n"
    "// Mirrors the CPU implementations in quants.c/model.c bit-layout for bit-layout.\n"
    "#include <metal_stdlib>\n"
    "using namespace metal;\n"
    "\n"
    "// ---------------------------------------------------------------- rmsnorm\n"
    "\n"
    "// One threadgroup per column: a prompt batch normalizes every token in one\n"
    "// dispatch instead of n. Strides are explicit because x and y scratch can be\n"
    "// strided differently (n_embd vs xdim).\n"
    "struct norm_args { int n, x_stride, y_stride; float eps; };\n"
    "\n"
    "kernel void k_rmsnorm(device const float *x_all [[buffer(0)]],\n"
    "                      device float       *y_all [[buffer(1)]],\n"
    "                      device const float *w     [[buffer(2)]],\n"
    "                      constant norm_args &a     [[buffer(3)]],\n"
    "                      uint3 tid3 [[thread_position_in_threadgroup]],\n"
    "                      uint3 tpg3 [[threads_per_threadgroup]],\n"
    "                      uint3 tgpig [[threadgroup_position_in_grid]]) {\n"
    "    threadgroup float red[256];\n"
    "    uint tid = tid3.x, tpg = tpg3.x;\n"
    "    int n = a.n;\n"
    "    float eps = a.eps;\n"
    "    device const float *x = x_all + (ulong)tgpig.x * a.x_stride;\n"
    "    device float       *y = y_all + (ulong)tgpig.x * a.y_stride;\n"
    "    float s = 0;\n"
    "    for (int i = tid; i < n; i += tpg) s += x[i] * x[i];\n"
    "    red[tid] = s;\n"
    "    threadgroup_barrier(mem_flags::mem_threadgroup);\n"
    "    for (uint off = tpg / 2; off > 0; off >>= 1) {\n"
    "        if (tid < off) red[tid] += red[tid + off];\n"
    "        threadgroup_barrier(mem_flags::mem_threadgroup);\n"
    "    }\n"
    "    float r = rsqrt(red[0] / n + eps);\n"
    "    for (int i = tid; i < n; i += tpg) y[i] = x[i] * r * w[i];\n"
    "}\n"
    "\n"
    "// per-head RMSNorm (qwen3 Q/K norm): one threadgroup per head\n"
    "kernel void k_qknorm(device float       *v   [[buffer(0)]],\n"
    "                     device const float *w   [[buffer(1)]],\n"
    "                     constant int       &hd  [[buffer(2)]],\n"
    "                     constant float     &eps [[buffer(3)]],\n"
    "                     uint h   [[threadgroup_position_in_grid]],\n"
    "                     uint tid [[thread_position_in_threadgroup]],\n"
    "                     uint tpg [[threads_per_threadgroup]]) {\n"
    "    threadgroup float red[128];\n"
    "    device float *x = v + h * hd;\n"
    "    float s = 0;\n"
    "    for (int i = tid; i < hd; i += tpg) s += x[i] * x[i];\n"
    "    red[tid] = s;\n"
    "    threadgroup_barrier(mem_flags::mem_threadgroup);\n"
    "    for (uint off = tpg / 2; off > 0; off >>= 1) {\n"
    "        if (tid < off) red[tid] += red[tid + off];\n"
    "        threadgroup_barrier(mem_flags::mem_threadgroup);\n"
    "    }\n"
    "    float r = rsqrt(red[0] / hd + eps);\n"
    "    for (int i = tid; i < hd; i += tpg) x[i] = x[i] * r * w[i];\n"
    "}\n"
    "\n"
    "kernel void k_head_rmsnorm(device const float *src [[buffer(0)]],\n"
    "                           device float       *dst [[buffer(1)]],\n"
    "                           device const float *w   [[buffer(2)]],\n"
    "                           constant int       &hd  [[buffer(3)]],\n"
    "                           constant float     &eps [[buffer(4)]],\n"
    "                           constant int       &has_weight [[buffer(5)]],\n"
    "                           uint h   [[threadgroup_position_in_grid]],\n"
    "                           uint tid [[thread_position_in_threadgroup]],\n"
    "                           uint tpg [[threads_per_threadgroup]]) {\n"
    "    threadgroup float red[128];\n"
    "    device const float *x = src + h * hd;\n"
    "    device float *y = dst + h * hd;\n"
    "    float s = 0;\n"
    "    for (int i = tid; i < hd; i += tpg) s += x[i] * x[i];\n"
    "    red[tid] = s;\n"
    "    threadgroup_barrier(mem_flags::mem_threadgroup);\n"
    "    for (uint off = tpg / 2; off > 0; off >>= 1) {\n"
    "        if (tid < off) red[tid] += red[tid + off];\n"
    "        threadgroup_barrier(mem_flags::mem_threadgroup);\n"
    "    }\n"
    "    float r = rsqrt(red[0] / hd + eps);\n"
    "    for (int i = tid; i < hd; i += tpg)\n"
    "        y[i] = x[i] * r * (has_weight ? w[i] : 1.0f);\n"
    "}\n"
    "\n"
    "// ---------------------------------------------------------------- matvec\n"
    "// One simdgroup (32 lanes) per output row; lanes stride over blocks.\n"
    "//\n"
    "// n_col > 1 turns this into a matmul: the simdgroup walks its weight row once\n"
    "// per column, so for a prompt batch the row is fetched from device memory on\n"
    "// the first column and served from cache for the rest — prefill stops paying\n"
    "// the whole weight matrix per token. The arithmetic per output element is\n"
    "// character-for-character what n_col == 1 does (same lane striding, same\n"
    "// simd_sum), so batched prefill stays bit-identical to per-token submits,\n"
    "// which is what the CPU==GPU gate requires.\n"
    "//\n"
    "// col_tile trades the two off: one threadgroup per row over ALL columns gets\n"
    "// maximum cache reuse but serializes the batch and starves the GPU of\n"
    "// threadgroups; col_tile columns per threadgroup keeps grid.y parallelism\n"
    "// while still amortizing each weight fetch col_tile ways.\n"
    "//\n"
    "// x and y strides are explicit because they are NOT always n_in/n_out: the\n"
    "// xb scratch is strided by xdim = max(q_dim, n_embd).\n"
    "\n"
    "struct mv_args {\n"
    "    int   n_in;\n"
    "    int   n_out;\n"
    "    ulong w_off;      // tensor byte offset inside the weight buffer\n"
    "    int   has_bias;\n"
    "    int   n_col;      // columns (prompt tokens) processed by this dispatch\n"
    "    int   x_stride;   // elements between consecutive columns of x\n"
    "    int   y_stride;   // elements between consecutive columns of y\n"
    "    int   col_tile;   // columns per threadgroup (grid.y tiles the rest)\n"
    "};\n"
    "\n"
    "// The loop bound is uniform across the simdgroup, so every lane reaches each\n"
    "// simd_sum in MV_TAIL the same number of times — a divergent simd_sum would\n"
    "// be undefined.\n"
    "#define MV_HEAD \\\n"
    "    uint row = tgpig.x * (ntg.x / 32) + sgitg; \\\n"
    "    if (row >= (uint)a.n_out) return; \\\n"
    "    int col_lo = (int)tgpig.y * a.col_tile; \\\n"
    "    int col_hi = min(col_lo + a.col_tile, a.n_col); \\\n"
    "    for (int col = col_lo; col < col_hi; col++) { \\\n"
    "    device const float *x = x_all + (ulong)col * a.x_stride; \\\n"
    "    device float       *y = y_all + (ulong)col * a.y_stride;\n"
    "\n"
    "#define MV_TAIL \\\n"
    "    s = simd_sum(s); \\\n"
    "    if (tiisg == 0) y[row] = a.has_bias ? s + bias[row] : s; \\\n"
    "    }\n"
    "\n"
    "#define MV_PARAMS \\\n"
    "    device const uchar *wb    [[buffer(0)]], \\\n"
    "    device const float *x_all [[buffer(1)]], \\\n"
    "    device float       *y_all [[buffer(2)]], \\\n"
    "    constant mv_args   &a     [[buffer(3)]], \\\n"
    "    device const float *bias  [[buffer(4)]], \\\n"
    "    uint  sgitg [[simdgroup_index_in_threadgroup]], \\\n"
    "    uint  tiisg [[thread_index_in_simdgroup]], \\\n"
    "    uint3 tgpig [[threadgroup_position_in_grid]], \\\n"
    "    uint3 ntg   [[threads_per_threadgroup]]\n"
    "\n"
    "kernel void k_mv_f32(MV_PARAMS) {\n"
    "    MV_HEAD;\n"
    "    device const float *rw = (device const float *)(wb + a.w_off) + (ulong)row * a.n_in;\n"
    "    float s = 0;\n"
    "    for (int i = tiisg; i < a.n_in; i += 32) s += rw[i] * x[i];\n"
    "    MV_TAIL;\n"
    "}\n"
    "\n"
    "kernel void k_mv_f16(MV_PARAMS) {\n"
    "    MV_HEAD;\n"
    "    device const half *rw = (device const half *)(wb + a.w_off) + (ulong)row * a.n_in;\n"
    "    float s = 0;\n"
    "    for (int i = tiisg; i < a.n_in; i += 32) s += (float)rw[i] * x[i];\n"
    "    MV_TAIL;\n"
    "}\n"
    "\n"
    "kernel void k_mv_q8_0(MV_PARAMS) {\n"
    "    MV_HEAD;\n"
    "    int nb = a.n_in / 32;\n"
    "    device const uchar *rw = wb + a.w_off + (ulong)row * nb * 34;\n"
    "    float s = 0;\n"
    "    for (int b = tiisg; b < nb; b += 32) {\n"
    "        device const uchar *blk = rw + (ulong)b * 34;\n"
    "        float d = (float)*(device const half *)blk;\n"
    "        device const char *q = (device const char *)(blk + 2);\n"
    "        device const float *xp = x + b * 32;\n"
    "        float t = 0;\n"
    "        for (int j = 0; j < 32; j++) t += (float)q[j] * xp[j];\n"
    "        s += d * t;\n"
    "    }\n"
    "    MV_TAIL;\n"
    "}\n"
    "\n"
    "kernel void k_mv_q4_0(MV_PARAMS) {\n"
    "    MV_HEAD;\n"
    "    int nb = a.n_in / 32;\n"
    "    device const uchar *rw = wb + a.w_off + (ulong)row * nb * 18;\n"
    "    float s = 0;\n"
    "    for (int b = tiisg; b < nb; b += 32) {\n"
    "        device const uchar *blk = rw + (ulong)b * 18;\n"
    "        float d = (float)*(device const half *)blk;\n"
    "        device const uchar *q = blk + 2;\n"
    "        device const float *xp = x + b * 32;\n"
    "        float t = 0;\n"
    "        for (int j = 0; j < 16; j++)\n"
    "            t += ((int)(q[j] & 0xF) - 8) * xp[j] + ((int)(q[j] >> 4) - 8) * xp[j + 16];\n"
    "        s += d * t;\n"
    "    }\n"
    "    MV_TAIL;\n"
    "}\n"
    "\n"
    "kernel void k_mv_q4_1(MV_PARAMS) {\n"
    "    MV_HEAD;\n"
    "    int nb = a.n_in / 32;\n"
    "    device const uchar *rw = wb + a.w_off + (ulong)row * nb * 20;\n"
    "    float s = 0;\n"
    "    for (int b = tiisg; b < nb; b += 32) {\n"
    "        device const uchar *blk = rw + (ulong)b * 20;\n"
    "        float d = (float)*(device const half *)blk;\n"
    "        float mm = (float)*(device const half *)(blk + 2);\n"
    "        device const uchar *q = blk + 4;\n"
    "        device const float *xp = x + b * 32;\n"
    "        float t = 0, sx = 0;\n"
    "        for (int j = 0; j < 16; j++) {\n"
    "            t += (float)(q[j] & 0xF) * xp[j] + (float)(q[j] >> 4) * xp[j + 16];\n"
    "            sx += xp[j] + xp[j + 16];\n"
    "        }\n"
    "        s += d * t + mm * sx;\n"
    "    }\n"
    "    MV_TAIL;\n"
    "}\n"
    "\n"
    "kernel void k_mv_q5_0(MV_PARAMS) {\n"
    "    MV_HEAD;\n"
    "    int nb = a.n_in / 32;\n"
    "    device const uchar *rw = wb + a.w_off + (ulong)row * nb * 22;\n"
    "    float s = 0;\n"
    "    for (int b = tiisg; b < nb; b += 32) {\n"
    "        device const uchar *blk = rw + (ulong)b * 22;\n"
    "        float d = (float)*(device const half *)blk;\n"
    "        uint qh = (uint)blk[2] | ((uint)blk[3] << 8) |\n"
    "                  ((uint)blk[4] << 16) | ((uint)blk[5] << 24);\n"
    "        device const uchar *q = blk + 6;\n"
    "        device const float *xp = x + b * 32;\n"
    "        float t = 0;\n"
    "        for (int j = 0; j < 16; j++) {\n"
    "            int x0 = (int)((q[j] & 0xF) | (((qh >> j) & 1u) << 4)) - 16;\n"
    "            int x1 = (int)((q[j] >> 4)  | (((qh >> (j + 16)) & 1u) << 4)) - 16;\n"
    "            t += x0 * xp[j] + x1 * xp[j + 16];\n"
    "        }\n"
    "        s += d * t;\n"
    "    }\n"
    "    MV_TAIL;\n"
    "}\n"
    "\n"
    "kernel void k_mv_q5_1(MV_PARAMS) {\n"
    "    MV_HEAD;\n"
    "    int nb = a.n_in / 32;\n"
    "    device const uchar *rw = wb + a.w_off + (ulong)row * nb * 24;\n"
    "    float s = 0;\n"
    "    for (int b = tiisg; b < nb; b += 32) {\n"
    "        device const uchar *blk = rw + (ulong)b * 24;\n"
    "        float d = (float)*(device const half *)blk;\n"
    "        float mm = (float)*(device const half *)(blk + 2);\n"
    "        uint qh = (uint)blk[4] | ((uint)blk[5] << 8) |\n"
    "                  ((uint)blk[6] << 16) | ((uint)blk[7] << 24);\n"
    "        device const uchar *q = blk + 8;\n"
    "        device const float *xp = x + b * 32;\n"
    "        float t = 0, sx = 0;\n"
    "        for (int j = 0; j < 16; j++) {\n"
    "            t += (float)((q[j] & 0xF) | (((qh >> j) & 1u) << 4)) * xp[j] +\n"
    "                 (float)((q[j] >> 4)  | (((qh >> (j + 16)) & 1u) << 4)) * xp[j + 16];\n"
    "            sx += xp[j] + xp[j + 16];\n"
    "        }\n"
    "        s += d * t + mm * sx;\n"
    "    }\n"
    "    MV_TAIL;\n"
    "}\n"
    "\n"
    "static inline void get_scale_min_k4(int j, device const uchar *q,\n"
    "                                    thread uchar *d, thread uchar *m) {\n"
    "    if (j < 4) {\n"
    "        *d = q[j] & 63;\n"
    "        *m = q[j + 4] & 63;\n"
    "    } else {\n"
    "        *d = (q[j + 4] & 0xF) | ((q[j - 4] >> 6) << 4);\n"
    "        *m = (q[j + 4] >> 4)  | ((q[j    ] >> 6) << 4);\n"
    "    }\n"
    "}\n"
    "\n"
    "kernel void k_mv_q4_K(MV_PARAMS) {\n"
    "    MV_HEAD;\n"
    "    int nb = a.n_in / 256;\n"
    "    device const uchar *rw = wb + a.w_off + (ulong)row * nb * 144;\n"
    "    float s = 0;\n"
    "    for (int b = tiisg; b < nb; b += 32) {\n"
    "        device const uchar *blk = rw + (ulong)b * 144;\n"
    "        float d    = (float)*(device const half *)blk;\n"
    "        float dmin = (float)*(device const half *)(blk + 2);\n"
    "        device const uchar *sc = blk + 4;\n"
    "        device const uchar *q  = blk + 16;\n"
    "        device const float *xp = x + b * 256;\n"
    "        int is = 0;\n"
    "        for (int j = 0; j < 256; j += 64) {\n"
    "            uchar s1, m1, s2, m2;\n"
    "            get_scale_min_k4(is + 0, sc, &s1, &m1);\n"
    "            get_scale_min_k4(is + 1, sc, &s2, &m2);\n"
    "            float d1 = d * s1, mm1 = dmin * m1;\n"
    "            float d2 = d * s2, mm2 = dmin * m2;\n"
    "            float t1 = 0, t2 = 0, sx1 = 0, sx2 = 0;\n"
    "            for (int l = 0; l < 32; l++) {\n"
    "                t1 += (float)(q[l] & 0xF) * xp[l];      sx1 += xp[l];\n"
    "                t2 += (float)(q[l] >> 4)  * xp[l + 32]; sx2 += xp[l + 32];\n"
    "            }\n"
    "            s += d1 * t1 - mm1 * sx1 + d2 * t2 - mm2 * sx2;\n"
    "            q += 32; is += 2; xp += 64;\n"
    "        }\n"
    "    }\n"
    "    MV_TAIL;\n"
    "}\n"
    "\n"
    "kernel void k_mv_q5_K(MV_PARAMS) {\n"
    "    MV_HEAD;\n"
    "    int nb = a.n_in / 256;\n"
    "    device const uchar *rw = wb + a.w_off + (ulong)row * nb * 176;\n"
    "    float s = 0;\n"
    "    for (int b = tiisg; b < nb; b += 32) {\n"
    "        device const uchar *blk = rw + (ulong)b * 176;\n"
    "        float d    = (float)*(device const half *)blk;\n"
    "        float dmin = (float)*(device const half *)(blk + 2);\n"
    "        device const uchar *sc = blk + 4;\n"
    "        device const uchar *qh = blk + 16;\n"
    "        device const uchar *q  = blk + 48;\n"
    "        device const float *xp = x + b * 256;\n"
    "        int is = 0;\n"
    "        uchar u1 = 1, u2 = 2;\n"
    "        for (int j = 0; j < 256; j += 64) {\n"
    "            uchar s1, m1, s2, m2;\n"
    "            get_scale_min_k4(is + 0, sc, &s1, &m1);\n"
    "            get_scale_min_k4(is + 1, sc, &s2, &m2);\n"
    "            float d1 = d * s1, mm1 = dmin * m1;\n"
    "            float d2 = d * s2, mm2 = dmin * m2;\n"
    "            for (int l = 0; l < 32; l++) {\n"
    "                s += (d1 * (float)((q[l] & 0xF) + ((qh[l] & u1) ? 16 : 0)) - mm1) * xp[l];\n"
    "                s += (d2 * (float)((q[l] >> 4)  + ((qh[l] & u2) ? 16 : 0)) - mm2) * xp[l + 32];\n"
    "            }\n"
    "            q += 32; is += 2; xp += 64; u1 <<= 2; u2 <<= 2;\n"
    "        }\n"
    "    }\n"
    "    MV_TAIL;\n"
    "}\n"
    "\n"
    "kernel void k_mv_q6_K(MV_PARAMS) {\n"
    "    MV_HEAD;\n"
    "    int nb = a.n_in / 256;\n"
    "    device const uchar *rw = wb + a.w_off + (ulong)row * nb * 210;\n"
    "    float s = 0;\n"
    "    for (int b = tiisg; b < nb; b += 32) {\n"
    "        device const uchar *blk = rw + (ulong)b * 210;\n"
    "        device const uchar *ql = blk;\n"
    "        device const uchar *qh = blk + 128;\n"
    "        device const char  *sc = (device const char *)(blk + 192);\n"
    "        float d = (float)*(device const half *)(blk + 208);\n"
    "        device const float *xp = x + b * 256;\n"
    "        for (int half_i = 0; half_i < 2; half_i++) {\n"
    "            float t[8] = {0, 0, 0, 0, 0, 0, 0, 0};\n"
    "            for (int l = 0; l < 32; l++) {\n"
    "                int is = (l / 16) & 1;\n"
    "                int q1 = (int)((ql[l]      & 0xF) | (((qh[l] >> 0) & 3) << 4)) - 32;\n"
    "                int q2 = (int)((ql[l + 32] & 0xF) | (((qh[l] >> 2) & 3) << 4)) - 32;\n"
    "                int q3 = (int)((ql[l]      >> 4)  | (((qh[l] >> 4) & 3) << 4)) - 32;\n"
    "                int q4 = (int)((ql[l + 32] >> 4)  | (((qh[l] >> 6) & 3) << 4)) - 32;\n"
    "                t[is * 4 + 0] += q1 * xp[l];\n"
    "                t[is * 4 + 1] += q2 * xp[l + 32];\n"
    "                t[is * 4 + 2] += q3 * xp[l + 64];\n"
    "                t[is * 4 + 3] += q4 * xp[l + 96];\n"
    "            }\n"
    "            s += d * (sc[0] * t[0] + sc[2] * t[1] + sc[4] * t[2] + sc[6] * t[3] +\n"
    "                      sc[1] * t[4] + sc[3] * t[5] + sc[5] * t[6] + sc[7] * t[7]);\n"
    "            ql += 64; qh += 32; sc += 8; xp += 128;\n"
    "        }\n"
    "    }\n"
    "    MV_TAIL;\n"
    "}\n"
    "\n"
    "constant float kv_mxfp4[16] = {\n"
    "     0.0f,  0.5f,  1.0f,  1.5f,  2.0f,  3.0f,  4.0f,  6.0f,\n"
    "     0.0f, -0.5f, -1.0f, -1.5f, -2.0f, -3.0f, -4.0f, -6.0f,\n"
    "};\n"
    "\n"
    "kernel void k_mv_mxfp4(MV_PARAMS) {\n"
    "    MV_HEAD;\n"
    "    int nb = a.n_in / 32;\n"
    "    device const uchar *rw = wb + a.w_off + (ulong)row * nb * 17;\n"
    "    float s = 0;\n"
    "    for (int b = tiisg; b < nb; b += 32) {\n"
    "        device const uchar *blk = rw + (ulong)b * 17;\n"
    "        float d = ldexp(1.0f, (int)blk[0] - 127);\n"
    "        device const uchar *q = blk + 1;\n"
    "        device const float *xp = x + b * 32;\n"
    "        float t = 0;\n"
    "        for (int j = 0; j < 16; j++) {\n"
    "            t += kv_mxfp4[q[j] & 0xF] * xp[j];\n"
    "            t += kv_mxfp4[q[j] >> 4]  * xp[j + 16];\n"
    "        }\n"
    "        s += d * t;\n"
    "    }\n"
    "    MV_TAIL;\n"
    "}\n"
    "\n"
    "// ---------------------------------------------------------------- rope\n"
    "\n"
    "// pos is the FIRST column's position; column c rotates at pos + c, so a whole\n"
    "// prompt batch ropes in one dispatch (grid.z selects the column).\n"
    "struct rope_args {\n"
    "    int   head_dim, n_heads, half_dim, pos, neox;\n"
    "    float mscale;\n"
    "    int   stride;     // elements between consecutive columns\n"
    "};\n"
    "\n"
    "kernel void k_rope(device float       *v_all [[buffer(0)]],\n"
    "                   device const float *fr    [[buffer(1)]],\n"
    "                   constant rope_args &a     [[buffer(2)]],\n"
    "                   uint3 gid [[thread_position_in_grid]]) {\n"
    "    int j = gid.x, h = gid.y, col = gid.z;\n"
    "    if (j >= a.half_dim || h >= a.n_heads) return;\n"
    "    float ang = (a.pos + col) * fr[j];\n"
    "    float c = cos(ang) * a.mscale, s = sin(ang) * a.mscale;\n"
    "    device float *v = v_all + (ulong)col * a.stride;\n"
    "    device float *p = v + h * a.head_dim;\n"
    "    int i0 = a.neox ? j : 2 * j;\n"
    "    int i1 = a.neox ? j + a.half_dim : i0 + 1;\n"
    "    float x0 = p[i0], x1 = p[i1];\n"
    "    p[i0] = x0 * c - x1 * s;\n"
    "    p[i1] = x0 * s + x1 * c;\n"
    "}\n"
    "\n"
    "// ---------------------------------------------------------------- kv store\n"
    "// The KV cache is either fp16 (2 bytes/value) or q8_0 (32 values per 34-byte\n"
    "// block: one fp16 scale + 32 int8 quants). Offsets are byte offsets so the CPU\n"
    "// and Metal paths share the same cache layout.\n"
    "\n"
    "static inline ulong kv_row_bytes(int kv_dim, int q8) {\n"
    "    return q8 ? (ulong)(kv_dim / 32) * 34 : (ulong)kv_dim * 2;\n"
    "}\n"
    "\n"
    "static inline ulong kv_head_off(int kvh, int hd, int q8) {\n"
    "    return q8 ? (ulong)(kvh * hd / 32) * 34 : (ulong)(kvh * hd) * 2;\n"
    "}\n"
    "\n"
    "static inline void kv_store_row(device uchar *cache, device const float *src,\n"
    "                                int q8, uint i) {\n"
    "    if (q8) {\n"
    "        device uchar *blk = cache + (ulong)i * 34;\n"
    "        device half *dptr = (device half *)blk;\n"
    "        device char *q = (device char *)(blk + 2);\n"
    "        device const float *x = src + i * 32;\n"
    "        float amax = 0;\n"
    "        for (int j = 0; j < 32; j++) amax = max(amax, fabs(x[j]));\n"
    "        float d = amax / 127.0f;\n"
    "        float id = d > 0 ? 1.0f / d : 0.0f;\n"
    "        *dptr = (half)d;\n"
    "        for (int j = 0; j < 32; j++) q[j] = (char)round(x[j] * id);\n"
    "    } else {\n"
    "        ((device half *)cache)[i] = (half)src[i];\n"
    "    }\n"
    "}\n"
    "\n"
    "static inline float kv_dot(device const uchar *row, device const float *qh,\n"
    "                           int hd, int q8) {\n"
    "    float s = 0;\n"
    "    if (q8) {\n"
    "        for (int b = 0; b < hd / 32; b++) {\n"
    "            device const uchar *blk = row + (ulong)b * 34;\n"
    "            float d = (float)*(device const half *)blk;\n"
    "            device const char *q = (device const char *)(blk + 2);\n"
    "            device const float *xp = qh + b * 32;\n"
    "            float t = 0;\n"
    "            for (int j = 0; j < 32; j += 2)\n"
    "                t += xp[j] * (float)q[j] + xp[j + 1] * (float)q[j + 1];\n"
    "            s += d * t;\n"
    "        }\n"
    "    } else {\n"
    "        device const half *k = (device const half *)row;\n"
    "        for (int i = 0; i < hd; i++) s += qh[i] * (float)k[i];\n"
    "    }\n"
    "    return s;\n"
    "}\n"
    "\n"
    "static inline float2 kv_pair(device const uchar *row, int i2, int q8) {\n"
    "    if (q8) {\n"
    "        device const uchar *blk = row + (ulong)(i2 / 16) * 34;\n"
    "        float d = (float)*(device const half *)blk;\n"
    "        device const char *q = (device const char *)(blk + 2);\n"
    "        int j = (2 * i2) & 31;\n"
    "        return float2(d * (float)q[j], d * (float)q[j + 1]);\n"
    "    }\n"
    "    device const half *h = (device const half *)row + 2 * i2;\n"
    "    return float2((float)h[0], (float)h[1]);\n"
    "}\n"
    "\n"
    "// off is the FIRST column's byte offset; column c lands row_b bytes further on,\n"
    "// so a prompt batch stores every token's K/V in one dispatch (grid.y = column).\n"
    "struct store_args { int kv_dim, q8, stride; ulong off, row_b; };\n"
    "\n"
    "kernel void k_store_kv(device const float *k_all [[buffer(0)]],\n"
    "                       device const float *v_all [[buffer(1)]],\n"
    "                       device uchar       *kc [[buffer(2)]],\n"
    "                       device uchar       *vc [[buffer(3)]],\n"
    "                       constant store_args &a [[buffer(4)]],\n"
    "                       uint2 gid [[thread_position_in_grid]]) {\n"
    "    int n = a.q8 ? a.kv_dim / 32 : a.kv_dim;\n"
    "    uint i = gid.x, col = gid.y;\n"
    "    if ((int)i < n) {\n"
    "        ulong off = a.off + (ulong)col * a.row_b;\n"
    "        kv_store_row(kc + off, k_all + (ulong)col * a.stride, a.q8, i);\n"
    "        kv_store_row(vc + off, v_all + (ulong)col * a.stride, a.q8, i);\n"
    "    }\n"
    "}\n"
    "\n"
    "// ---------------------------------------------------------------- attention\n"
    "// One threadgroup per head: scores -> softmax -> weighted value sum.\n"
    "\n"
    "// pos is the FIRST column's position; column c attends over [.., pos + c], so\n"
    "// a prompt batch runs every token's attention in one dispatch (grid.y = col).\n"
    "// Each column keeps its own score row and output slice, so the arithmetic per\n"
    "// (head, position) is exactly what a per-token dispatch computed.\n"
    "struct attn_args {\n"
    "    int   head_dim, n_head, n_head_kv, n_ctx, pos;\n"
    "    ulong l_off;      // this layer's byte offset into the kv cache\n"
    "    float scale;\n"
    "    int   q8;\n"
    "    int   window;     // sliding-window size for this layer (0 = full)\n"
    "    int   has_sinks;  // gpt-oss: per-head sink joins softmax denominator only\n"
    "    int   q_stride, att_stride, out_stride;\n"
    "};\n"
    "\n"
    "kernel void k_attn(device const float *q_all   [[buffer(0)]],\n"
    "                   device const uchar *kc      [[buffer(1)]],\n"
    "                   device const uchar *vc      [[buffer(2)]],\n"
    "                   device float       *att_all [[buffer(3)]],\n"
    "                   device float       *out_all [[buffer(4)]],\n"
    "                   constant attn_args &a   [[buffer(5)]],\n"
    "                   device const float *sinks [[buffer(6)]],\n"
    "                   uint3 tgpig [[threadgroup_position_in_grid]],\n"
    "                   uint3 tid3 [[thread_position_in_threadgroup]],\n"
    "                   uint3 tpg3 [[threads_per_threadgroup]]) {\n"
    "    threadgroup float red[256];\n"
    "    uint tid = tid3.x, tpg = tpg3.x;\n"
    "    uint h = tgpig.x, col = tgpig.y;\n"
    "    int hd = a.head_dim;\n"
    "    int kvh = h / (a.n_head / a.n_head_kv);\n"
    "    int kv_dim = a.n_head_kv * hd;\n"
    "    ulong row_b = kv_row_bytes(kv_dim, a.q8);\n"
    "    ulong base = a.l_off + kv_head_off(kvh, hd, a.q8);\n"
    "    int pos = a.pos + (int)col;\n"
    "    device const float *q = q_all + (ulong)col * a.q_stride;\n"
    "    device float *att = att_all + (ulong)col * a.att_stride;\n"
    "    device float *out = out_all + (ulong)col * a.out_stride;\n"
    "    device const float *qh = q + h * hd;\n"
    "    device float *ah = att + (ulong)h * a.n_ctx;\n"
    "    int t0 = 0;\n"
    "    if (a.window > 0 && pos - a.window + 1 > 0) t0 = pos - a.window + 1;\n"
    "\n"
    "    for (int t = t0 + tid; t <= pos; t += tpg) {\n"
    "        ah[t] = kv_dot(kc + base + (ulong)t * row_b, qh, hd, a.q8) * a.scale;\n"
    "    }\n"
    "    threadgroup_barrier(mem_flags::mem_device);\n"
    "\n"
    "    // max\n"
    "    float mx = -1e30f;\n"
    "    for (int t = t0 + tid; t <= pos; t += tpg) mx = max(mx, ah[t]);\n"
    "    if (a.has_sinks && tid == 0) mx = max(mx, sinks[h]);\n"
    "    red[tid] = mx;\n"
    "    threadgroup_barrier(mem_flags::mem_threadgroup);\n"
    "    for (uint off = tpg / 2; off > 0; off >>= 1) {\n"
    "        if (tid < off) red[tid] = max(red[tid], red[tid + off]);\n"
    "        threadgroup_barrier(mem_flags::mem_threadgroup);\n"
    "    }\n"
    "    mx = red[0];\n"
    "    threadgroup_barrier(mem_flags::mem_threadgroup);\n"
    "    // exp + sum\n"
    "    float sum = 0;\n"
    "    for (int t = t0 + tid; t <= pos; t += tpg) {\n"
    "        float e = exp(ah[t] - mx);\n"
    "        ah[t] = e;\n"
    "        sum += e;\n"
    "    }\n"
    "    if (a.has_sinks && tid == 0) sum += exp(sinks[h] - mx);\n"
    "    red[tid] = sum;\n"
    "    threadgroup_barrier(mem_flags::mem_threadgroup);\n"
    "    for (uint off = tpg / 2; off > 0; off >>= 1) {\n"
    "        if (tid < off) red[tid] += red[tid + off];\n"
    "        threadgroup_barrier(mem_flags::mem_threadgroup);\n"
    "    }\n"
    "    sum = red[0];\n"
    "    threadgroup_barrier(mem_flags::mem_device);\n"
    "\n"
    "    for (int i = tid; i < hd; i += tpg) {\n"
    "        float o = 0;\n"
    "        for (int t = t0; t <= pos; t++)\n"
    "            o += ah[t] * kv_pair(vc + base + (ulong)t * row_b, i / 2, a.q8)[i & 1];\n"
    "        out[h * hd + i] = o / sum;\n"
    "    }\n"
    "}\n"
    "\n"
    "// ---------------------------------------------------------------- elementwise\n"
    "\n"
    "kernel void k_silu_mul(device float       *g [[buffer(0)]],\n"
    "                       device const float *u [[buffer(1)]],\n"
    "                       constant int       &n [[buffer(2)]],\n"
    "                       uint i [[thread_position_in_grid]]) {\n"
    "    if ((int)i < n) {\n"
    "        float x = g[i];\n"
    "        g[i] = (x / (1.0f + exp(-x))) * u[i];\n"
    "    }\n"
    "}\n"
    "\n"
    "kernel void k_gelu_mul(device float       *g [[buffer(0)]],\n"
    "                       device const float *u [[buffer(1)]],\n"
    "                       constant int       &n [[buffer(2)]],\n"
    "                       uint i [[thread_position_in_grid]]) {\n"
    "    if ((int)i < n) {\n"
    "        float x = g[i];\n"
    "        // Metal compiles with fast math, where tanh() is evaluated through\n"
    "        // exp(2a): for large |a| that overflows to inf and inf/inf yields NaN,\n"
    "        // while the CPU oracle's libm tanhf saturates. Gemma-class models\n"
    "        // reach it — gemma-3-4b's layer-0 gate produced NaN logits here, and\n"
    "        // the model emitted only token 0. Clamping to a magnitude where tanh\n"
    "        // is already exactly +/-1.0f in fp32 cannot change any representable\n"
    "        // result, so this guard is invisible to the identity gates. Same\n"
    "        // hazard, same fix as the `g < -80` early-out in the CPU silu path.\n"
    "        float a = 0.7978845608f * (x + 0.044715f * x * x * x);\n"
    "        float t = tanh(clamp(a, -16.0f, 16.0f));\n"
    "        g[i] = 0.5f * x * (1.0f + t) * u[i];\n"
    "    }\n"
    "}\n"
    "\n"
    "kernel void k_add(device float       *x [[buffer(0)]],\n"
    "                  device const float *d [[buffer(1)]],\n"
    "                  constant int       &n [[buffer(2)]],\n"
    "                  uint i [[thread_position_in_grid]]) {\n"
    "    if ((int)i < n) x[i] += d[i];\n"
    "}\n"
    "\n"
    "kernel void k_scale(device float       *x [[buffer(0)]],\n"
    "                    constant float     &s [[buffer(1)]],\n"
    "                    constant int       &n [[buffer(2)]],\n"
    "                    uint i [[thread_position_in_grid]]) {\n"
    "    if ((int)i < n) x[i] *= s;\n"
    "}\n"
    "\n"
    "kernel void k_head_transform(device float     *logits [[buffer(0)]],\n"
    "                             device const int *suppress [[buffer(1)]],\n"
    "                             constant int     &nv [[buffer(2)]],\n"
    "                             constant float   &softcap [[buffer(3)]],\n"
    "                             constant int     &ns [[buffer(4)]],\n"
    "                             uint i [[thread_position_in_grid]]) {\n"
    "    if ((int)i < nv && softcap > 0.0f)\n"
    "        logits[i] = softcap * tanh(logits[i] / softcap);\n"
    "    if ((int)i < ns) {\n"
    "        int tok = suppress[i];\n"
    "        if (tok >= 0 && tok < nv) logits[tok] = -1e30f;\n"
    "    }\n"
    "}\n"
    "\n"
    "// -------------------------------------------------------------- sparse MoE\n"
    "// Plain router + fused-3D expert layout. This is the Metal twin of the first\n"
    "// CUDA MoE slice: softmax -> top-k -> renormalize on device, then one indirect\n"
    "// expert matvec launch per projection.\n"
    "\n"
    "kernel void k_moe_route(device const float *logits [[buffer(0)]],\n"
    "                        device int         *sel    [[buffer(1)]],\n"
    "                        device float       *selw   [[buffer(2)]],\n"
    "                        constant int       &ne     [[buffer(3)]],\n"
    "                        constant int       &used   [[buffer(4)]],\n"
    "                        constant int       &tokens [[buffer(5)]],\n"
    "                        constant int       &ls     [[buffer(6)]],\n"
    "                        uint t [[thread_position_in_grid]]) {\n"
    "    if ((int)t >= tokens) return;\n"
    "    float lg[256];\n"
    "    device const float *src = logits + (ulong)t * ls;\n"
    "    for (int e = 0; e < ne; e++) lg[e] = src[e];\n"
    "\n"
    "    float mx = lg[0];\n"
    "    for (int e = 1; e < ne; e++)\n"
    "        if (lg[e] > mx) mx = lg[e];\n"
    "    float sum = 0.0f;\n"
    "    for (int e = 0; e < ne; e++) {\n"
    "        float p = exp(lg[e] - mx);\n"
    "        lg[e] = p;\n"
    "        sum += p;\n"
    "    }\n"
    "    for (int e = 0; e < ne; e++) lg[e] /= sum;\n"
    "\n"
    "    device int *ts = sel + (ulong)t * used;\n"
    "    device float *tw = selw + (ulong)t * used;\n"
    "    float denom = 0.0f;\n"
    "    for (int s = 0; s < used; s++) {\n"
    "        int best = 0;\n"
    "        float bp = -1.0f;\n"
    "        for (int e = 0; e < ne; e++)\n"
    "            if (lg[e] > bp) { bp = lg[e]; best = e; }\n"
    "        ts[s] = best;\n"
    "        tw[s] = bp;\n"
    "        denom += bp;\n"
    "        lg[best] = -1.0f;\n"
    "    }\n"
    "    if (denom < 6.103515625e-5f) denom = 6.103515625e-5f;\n"
    "    for (int s = 0; s < used; s++) tw[s] /= denom;\n"
    "}\n"
    "\n"
    "struct moe_args {\n"
    "    int   n_in;\n"
    "    int   n_out;\n"
    "    ulong w_off;\n"
    "    ulong estride;\n"
    "    int   xs;\n"
    "    int   ys;\n"
    "    int   has_bias;\n"
    "    int   bias_stride;\n"
    "};\n"
    "\n"
    "#define MOE_MV_HEAD \\\n"
    "    uint row = tgpig.x * (ntg.x / 32) + sgitg; \\\n"
    "    if (row >= (uint)a.n_out) return; \\\n"
    "    device const uchar *wbase = wb + a.w_off + (ulong)sel[tgpig.y] * a.estride; \\\n"
    "    device const float *xp0 = x + (ulong)tgpig.y * a.xs; \\\n"
    "    float s = 0;\n"
    "\n"
    "#define MOE_MV_TAIL \\\n"
    "    s = simd_sum(s); \\\n"
    "    if (tiisg == 0) { \\\n"
    "        if (a.has_bias) s += bias[(ulong)sel[tgpig.y] * a.bias_stride + row]; \\\n"
    "        y[(ulong)tgpig.y * a.ys + row] = s; \\\n"
    "    }\n"
    "\n"
    "#define MOE_MV_PARAMS \\\n"
    "    device const uchar *wb  [[buffer(0)]], \\\n"
    "    device const float *x   [[buffer(1)]], \\\n"
    "    device float       *y   [[buffer(2)]], \\\n"
    "    constant moe_args  &a   [[buffer(3)]], \\\n"
    "    device const int   *sel [[buffer(4)]], \\\n"
    "    device const float *bias [[buffer(5)]], \\\n"
    "    uint  sgitg [[simdgroup_index_in_threadgroup]], \\\n"
    "    uint  tiisg [[thread_index_in_simdgroup]], \\\n"
    "    uint3 tgpig [[threadgroup_position_in_grid]], \\\n"
    "    uint3 ntg   [[threads_per_threadgroup]]\n"
    "\n"
    "kernel void k_moe_mv_f32(MOE_MV_PARAMS) {\n"
    "    MOE_MV_HEAD;\n"
    "    device const float *rw = (device const float *)wbase + (ulong)row * a.n_in;\n"
    "    for (int i = tiisg; i < a.n_in; i += 32) s += rw[i] * xp0[i];\n"
    "    MOE_MV_TAIL;\n"
    "}\n"
    "\n"
    "kernel void k_moe_mv_f16(MOE_MV_PARAMS) {\n"
    "    MOE_MV_HEAD;\n"
    "    device const half *rw = (device const half *)wbase + (ulong)row * a.n_in;\n"
    "    for (int i = tiisg; i < a.n_in; i += 32) s += (float)rw[i] * xp0[i];\n"
    "    MOE_MV_TAIL;\n"
    "}\n"
    "\n"
    "kernel void k_moe_mv_q8_0(MOE_MV_PARAMS) {\n"
    "    MOE_MV_HEAD;\n"
    "    int nb = a.n_in / 32;\n"
    "    device const uchar *rw = wbase + (ulong)row * nb * 34;\n"
    "    for (int b = tiisg; b < nb; b += 32) {\n"
    "        device const uchar *blk = rw + (ulong)b * 34;\n"
    "        float d = (float)*(device const half *)blk;\n"
    "        device const char *q = (device const char *)(blk + 2);\n"
    "        device const float *xp = xp0 + b * 32;\n"
    "        float t = 0;\n"
    "        for (int j = 0; j < 32; j++) t += (float)q[j] * xp[j];\n"
    "        s += d * t;\n"
    "    }\n"
    "    MOE_MV_TAIL;\n"
    "}\n"
    "\n"
    "kernel void k_moe_mv_q4_0(MOE_MV_PARAMS) {\n"
    "    MOE_MV_HEAD;\n"
    "    int nb = a.n_in / 32;\n"
    "    device const uchar *rw = wbase + (ulong)row * nb * 18;\n"
    "    for (int b = tiisg; b < nb; b += 32) {\n"
    "        device const uchar *blk = rw + (ulong)b * 18;\n"
    "        float d = (float)*(device const half *)blk;\n"
    "        device const uchar *q = blk + 2;\n"
    "        device const float *xp = xp0 + b * 32;\n"
    "        float t = 0;\n"
    "        for (int j = 0; j < 16; j++)\n"
    "            t += ((int)(q[j] & 0xF) - 8) * xp[j] + ((int)(q[j] >> 4) - 8) * xp[j + 16];\n"
    "        s += d * t;\n"
    "    }\n"
    "    MOE_MV_TAIL;\n"
    "}\n"
    "\n"
    "kernel void k_moe_mv_q4_K(MOE_MV_PARAMS) {\n"
    "    MOE_MV_HEAD;\n"
    "    int nb = a.n_in / 256;\n"
    "    device const uchar *rw = wbase + (ulong)row * nb * 144;\n"
    "    for (int b = tiisg; b < nb; b += 32) {\n"
    "        device const uchar *blk = rw + (ulong)b * 144;\n"
    "        float d    = (float)*(device const half *)blk;\n"
    "        float dmin = (float)*(device const half *)(blk + 2);\n"
    "        device const uchar *sc = blk + 4;\n"
    "        device const uchar *q  = blk + 16;\n"
    "        device const float *xp = xp0 + b * 256;\n"
    "        int is = 0;\n"
    "        for (int j = 0; j < 256; j += 64) {\n"
    "            uchar s1, m1, s2, m2;\n"
    "            get_scale_min_k4(is + 0, sc, &s1, &m1);\n"
    "            get_scale_min_k4(is + 1, sc, &s2, &m2);\n"
    "            float d1 = d * s1, mm1 = dmin * m1;\n"
    "            float d2 = d * s2, mm2 = dmin * m2;\n"
    "            float t1 = 0, t2 = 0, sx1 = 0, sx2 = 0;\n"
    "            for (int l = 0; l < 32; l++) {\n"
    "                t1 += (float)(q[l] & 0xF) * xp[l];      sx1 += xp[l];\n"
    "                t2 += (float)(q[l] >> 4)  * xp[l + 32]; sx2 += xp[l + 32];\n"
    "            }\n"
    "            s += d1 * t1 - mm1 * sx1 + d2 * t2 - mm2 * sx2;\n"
    "            q += 32; is += 2; xp += 64;\n"
    "        }\n"
    "    }\n"
    "    MOE_MV_TAIL;\n"
    "}\n"
    "\n"
    "kernel void k_moe_mv_q5_K(MOE_MV_PARAMS) {\n"
    "    MOE_MV_HEAD;\n"
    "    int nb = a.n_in / 256;\n"
    "    device const uchar *rw = wbase + (ulong)row * nb * 176;\n"
    "    for (int b = tiisg; b < nb; b += 32) {\n"
    "        device const uchar *blk = rw + (ulong)b * 176;\n"
    "        float d    = (float)*(device const half *)blk;\n"
    "        float dmin = (float)*(device const half *)(blk + 2);\n"
    "        device const uchar *sc = blk + 4;\n"
    "        device const uchar *qh = blk + 16;\n"
    "        device const uchar *q  = blk + 48;\n"
    "        device const float *xp = xp0 + b * 256;\n"
    "        int is = 0;\n"
    "        uchar u1 = 1, u2 = 2;\n"
    "        for (int j = 0; j < 256; j += 64) {\n"
    "            uchar s1, m1, s2, m2;\n"
    "            get_scale_min_k4(is + 0, sc, &s1, &m1);\n"
    "            get_scale_min_k4(is + 1, sc, &s2, &m2);\n"
    "            float d1 = d * s1, mm1 = dmin * m1;\n"
    "            float d2 = d * s2, mm2 = dmin * m2;\n"
    "            for (int l = 0; l < 32; l++) {\n"
    "                s += (d1 * (float)((q[l] & 0xF) + ((qh[l] & u1) ? 16 : 0)) - mm1) * xp[l];\n"
    "                s += (d2 * (float)((q[l] >> 4)  + ((qh[l] & u2) ? 16 : 0)) - mm2) * xp[l + 32];\n"
    "            }\n"
    "            q += 32; is += 2; xp += 64; u1 <<= 2; u2 <<= 2;\n"
    "        }\n"
    "    }\n"
    "    MOE_MV_TAIL;\n"
    "}\n"
    "\n"
    "kernel void k_moe_mv_q6_K(MOE_MV_PARAMS) {\n"
    "    MOE_MV_HEAD;\n"
    "    int nb = a.n_in / 256;\n"
    "    device const uchar *rw = wbase + (ulong)row * nb * 210;\n"
    "    for (int b = tiisg; b < nb; b += 32) {\n"
    "        device const uchar *blk = rw + (ulong)b * 210;\n"
    "        device const uchar *ql = blk;\n"
    "        device const uchar *qh = blk + 128;\n"
    "        device const char  *sc = (device const char *)(blk + 192);\n"
    "        float d = (float)*(device const half *)(blk + 208);\n"
    "        device const float *xp = xp0 + b * 256;\n"
    "        for (int half_i = 0; half_i < 2; half_i++) {\n"
    "            float t[8] = {0, 0, 0, 0, 0, 0, 0, 0};\n"
    "            for (int l = 0; l < 32; l++) {\n"
    "                int is = (l / 16) & 1;\n"
    "                int q1 = (int)((ql[l]      & 0xF) | (((qh[l] >> 0) & 3) << 4)) - 32;\n"
    "                int q2 = (int)((ql[l + 32] & 0xF) | (((qh[l] >> 2) & 3) << 4)) - 32;\n"
    "                int q3 = (int)((ql[l]      >> 4)  | (((qh[l] >> 4) & 3) << 4)) - 32;\n"
    "                int q4 = (int)((ql[l + 32] >> 4)  | (((qh[l] >> 6) & 3) << 4)) - 32;\n"
    "                t[is * 4 + 0] += q1 * xp[l];\n"
    "                t[is * 4 + 1] += q2 * xp[l + 32];\n"
    "                t[is * 4 + 2] += q3 * xp[l + 64];\n"
    "                t[is * 4 + 3] += q4 * xp[l + 96];\n"
    "            }\n"
    "            s += d * (sc[0] * t[0] + sc[2] * t[1] + sc[4] * t[2] + sc[6] * t[3] +\n"
    "                      sc[1] * t[4] + sc[3] * t[5] + sc[5] * t[6] + sc[7] * t[7]);\n"
    "            ql += 64; qh += 32; sc += 8; xp += 128;\n"
    "        }\n"
    "    }\n"
    "    MOE_MV_TAIL;\n"
    "}\n"
    "\n"
    "kernel void k_moe_mv_mxfp4(MOE_MV_PARAMS) {\n"
    "    MOE_MV_HEAD;\n"
    "    int nb = a.n_in / 32;\n"
    "    device const uchar *rw = wbase + (ulong)row * nb * 17;\n"
    "    for (int b = tiisg; b < nb; b += 32) {\n"
    "        device const uchar *blk = rw + (ulong)b * 17;\n"
    "        float d = ldexp(1.0f, (int)blk[0] - 127);\n"
    "        device const uchar *q = blk + 1;\n"
    "        device const float *xp = xp0 + b * 32;\n"
    "        float t = 0;\n"
    "        for (int j = 0; j < 16; j++) {\n"
    "            t += kv_mxfp4[q[j] & 0xF] * xp[j];\n"
    "            t += kv_mxfp4[q[j] >> 4]  * xp[j + 16];\n"
    "        }\n"
    "        s += d * t;\n"
    "    }\n"
    "    MOE_MV_TAIL;\n"
    "}\n"
    "\n"
    "static inline float swiglu_oai(float g, float u) {\n"
    "    const float alpha = 1.702f, limit = 7.0f;\n"
    "    float x = g < limit ? g : limit;\n"
    "    float y = clamp(u, -limit, limit);\n"
    "    float gl = x < -50.0f ? 0.0f : x / (1.0f + exp(alpha * -x));\n"
    "    return gl * (y + 1.0f);\n"
    "}\n"
    "\n"
    "kernel void k_moe_actmul(device float       *gbuf [[buffer(0)]],\n"
    "                         device const float *ubuf [[buffer(1)]],\n"
    "                         constant int4      &args [[buffer(2)]],\n"
    "                         uint2 gid [[thread_position_in_grid]]) {\n"
    "    int nff = args.x, gss = args.y, uss = args.z, act = args.w;\n"
    "    int i = gid.x, slot = gid.y;\n"
    "    if (i >= nff) return;\n"
    "    device float *g = gbuf + (ulong)slot * gss;\n"
    "    device const float *u = ubuf + (ulong)slot * uss;\n"
    "    float x = g[i];\n"
    "    if (act == 2) {\n"
    "        g[i] = swiglu_oai(x, u[i]);\n"
    "    } else if (act == 1) {\n"
    "        float t = tanh(0.7978845608f * (x + 0.044715f * x * x * x));\n"
    "        g[i] = 0.5f * x * (1.0f + t) * u[i];\n"
    "    } else {\n"
    "        g[i] = (x / (1.0f + exp(-x))) * u[i];\n"
    "    }\n"
    "}\n"
    "\n"
    "kernel void k_moe_sum(device float       *out    [[buffer(0)]],\n"
    "                      device const float *eout   [[buffer(1)]],\n"
    "                      device const float *selw   [[buffer(2)]],\n"
    "                      device const float *dscale [[buffer(3)]],\n"
    "                      device const int   *sel    [[buffer(4)]],\n"
    "                      constant int       &n      [[buffer(5)]],\n"
    "                      constant int       &nslots [[buffer(6)]],\n"
    "                      constant int       &es     [[buffer(7)]],\n"
    "                      constant int       &has_dscale [[buffer(8)]],\n"
    "                      uint i [[thread_position_in_grid]]) {\n"
    "    if ((int)i >= n) return;\n"
    "    float s = 0.0f;\n"
    "    for (int slot = 0; slot < nslots; slot++) {\n"
    "        float w = selw[slot] * (has_dscale ? dscale[sel[slot]] : 1.0f);\n"
    "        s += w * eout[(ulong)slot * es + i];\n"
    "    }\n"
    "    out[i] = s;\n"
    "}\n"
    "\n"
;
