// Generated from kernels.metal by scripts/embed-metal.py — do not edit.
static const char *k_metal_src =
    "// Metal compute kernels: the full single-token forward pass.\n"
    "// Mirrors the CPU implementations in quants.c/model.c bit-layout for bit-layout.\n"
    "#include <metal_stdlib>\n"
    "using namespace metal;\n"
    "\n"
    "// ---------------------------------------------------------------- rmsnorm\n"
    "\n"
    "kernel void k_rmsnorm(device const float *x   [[buffer(0)]],\n"
    "                      device float       *y   [[buffer(1)]],\n"
    "                      device const float *w   [[buffer(2)]],\n"
    "                      constant int       &n   [[buffer(3)]],\n"
    "                      constant float     &eps [[buffer(4)]],\n"
    "                      uint tid [[thread_position_in_threadgroup]],\n"
    "                      uint tpg [[threads_per_threadgroup]]) {\n"
    "    threadgroup float red[256];\n"
    "    float s = 0;\n"
    "    for (int i = tid; i < n; i += tpg) s += x[i] * x[i];\n"
    "    red[tid] = s;\n"
    "    threadgroup_barrier(mem_flags::mem_threadgroup);\n"
    "    for (uint off = tpg / 2; off > 0; off >>= 1) {\n"
    "        if (tid < off) red[tid] += red[tid + off];\n"
    "        threadgroup_barrier(mem_flags::mem_threadgroup);\n"
    "    }\n"
    "    float r = rsqrt(red[0] / n + eps);\n"
    "    for (int i = tid; i < n; i += tpg) y[i] = x[i] * r * w[i];\n"
    "}\n"
    "\n"
    "// ---------------------------------------------------------------- matvec\n"
    "// One simdgroup (32 lanes) per output row; lanes stride over blocks.\n"
    "\n"
    "struct mv_args {\n"
    "    int   n_in;\n"
    "    int   n_out;\n"
    "    ulong w_off;      // tensor byte offset inside the weight buffer\n"
    "    int   has_bias;\n"
    "};\n"
    "\n"
    "#define MV_HEAD \\\n"
    "    uint row = tgpig.x * (ntg.x / 32) + sgitg; \\\n"
    "    if (row >= (uint)a.n_out) return;\n"
    "\n"
    "#define MV_TAIL \\\n"
    "    s = simd_sum(s); \\\n"
    "    if (tiisg == 0) y[row] = a.has_bias ? s + bias[row] : s;\n"
    "\n"
    "#define MV_PARAMS \\\n"
    "    device const uchar *wb   [[buffer(0)]], \\\n"
    "    device const float *x    [[buffer(1)]], \\\n"
    "    device float       *y    [[buffer(2)]], \\\n"
    "    constant mv_args   &a    [[buffer(3)]], \\\n"
    "    device const float *bias [[buffer(4)]], \\\n"
    "    uint  sgitg [[simdgroup_index_in_threadgroup]], \\\n"
    "    uint  tiisg [[thread_index_in_simdgroup]], \\\n"
    "    uint3 tgpig [[threadgroup_position_in_grid]], \\\n"
    "    uint3 ntg   [[threads_per_threadgroup]]\n"
    "\n"
    "kernel void k_mv_f32(MV_PARAMS) {\n"
    "    MV_HEAD;\n"
    "    device const float *rw = (device const float *)(wb + a.w_off) + (ulong)row * a.n_in;\n"
    "    float s = 0;\n"
    "    for (int i = tiisg; i < a.n_in; i += 32) s += rw[i] * x[i];\n"
    "    MV_TAIL;\n"
    "}\n"
    "\n"
    "kernel void k_mv_f16(MV_PARAMS) {\n"
    "    MV_HEAD;\n"
    "    device const half *rw = (device const half *)(wb + a.w_off) + (ulong)row * a.n_in;\n"
    "    float s = 0;\n"
    "    for (int i = tiisg; i < a.n_in; i += 32) s += (float)rw[i] * x[i];\n"
    "    MV_TAIL;\n"
    "}\n"
    "\n"
    "kernel void k_mv_q8_0(MV_PARAMS) {\n"
    "    MV_HEAD;\n"
    "    int nb = a.n_in / 32;\n"
    "    device const uchar *rw = wb + a.w_off + (ulong)row * nb * 34;\n"
    "    float s = 0;\n"
    "    for (int b = tiisg; b < nb; b += 32) {\n"
    "        device const uchar *blk = rw + (ulong)b * 34;\n"
    "        float d = (float)*(device const half *)blk;\n"
    "        device const char *q = (device const char *)(blk + 2);\n"
    "        device const float *xp = x + b * 32;\n"
    "        float t = 0;\n"
    "        for (int j = 0; j < 32; j++) t += (float)q[j] * xp[j];\n"
    "        s += d * t;\n"
    "    }\n"
    "    MV_TAIL;\n"
    "}\n"
    "\n"
    "kernel void k_mv_q4_0(MV_PARAMS) {\n"
    "    MV_HEAD;\n"
    "    int nb = a.n_in / 32;\n"
    "    device const uchar *rw = wb + a.w_off + (ulong)row * nb * 18;\n"
    "    float s = 0;\n"
    "    for (int b = tiisg; b < nb; b += 32) {\n"
    "        device const uchar *blk = rw + (ulong)b * 18;\n"
    "        float d = (float)*(device const half *)blk;\n"
    "        device const uchar *q = blk + 2;\n"
    "        device const float *xp = x + b * 32;\n"
    "        float t = 0;\n"
    "        for (int j = 0; j < 16; j++)\n"
    "            t += ((int)(q[j] & 0xF) - 8) * xp[j] + ((int)(q[j] >> 4) - 8) * xp[j + 16];\n"
    "        s += d * t;\n"
    "    }\n"
    "    MV_TAIL;\n"
    "}\n"
    "\n"
    "kernel void k_mv_q4_1(MV_PARAMS) {\n"
    "    MV_HEAD;\n"
    "    int nb = a.n_in / 32;\n"
    "    device const uchar *rw = wb + a.w_off + (ulong)row * nb * 20;\n"
    "    float s = 0;\n"
    "    for (int b = tiisg; b < nb; b += 32) {\n"
    "        device const uchar *blk = rw + (ulong)b * 20;\n"
    "        float d = (float)*(device const half *)blk;\n"
    "        float mm = (float)*(device const half *)(blk + 2);\n"
    "        device const uchar *q = blk + 4;\n"
    "        device const float *xp = x + b * 32;\n"
    "        float t = 0, sx = 0;\n"
    "        for (int j = 0; j < 16; j++) {\n"
    "            t += (float)(q[j] & 0xF) * xp[j] + (float)(q[j] >> 4) * xp[j + 16];\n"
    "            sx += xp[j] + xp[j + 16];\n"
    "        }\n"
    "        s += d * t + mm * sx;\n"
    "    }\n"
    "    MV_TAIL;\n"
    "}\n"
    "\n"
    "kernel void k_mv_q5_0(MV_PARAMS) {\n"
    "    MV_HEAD;\n"
    "    int nb = a.n_in / 32;\n"
    "    device const uchar *rw = wb + a.w_off + (ulong)row * nb * 22;\n"
    "    float s = 0;\n"
    "    for (int b = tiisg; b < nb; b += 32) {\n"
    "        device const uchar *blk = rw + (ulong)b * 22;\n"
    "        float d = (float)*(device const half *)blk;\n"
    "        uint qh = (uint)blk[2] | ((uint)blk[3] << 8) |\n"
    "                  ((uint)blk[4] << 16) | ((uint)blk[5] << 24);\n"
    "        device const uchar *q = blk + 6;\n"
    "        device const float *xp = x + b * 32;\n"
    "        float t = 0;\n"
    "        for (int j = 0; j < 16; j++) {\n"
    "            int x0 = (int)((q[j] & 0xF) | (((qh >> j) & 1u) << 4)) - 16;\n"
    "            int x1 = (int)((q[j] >> 4)  | (((qh >> (j + 16)) & 1u) << 4)) - 16;\n"
    "            t += x0 * xp[j] + x1 * xp[j + 16];\n"
    "        }\n"
    "        s += d * t;\n"
    "    }\n"
    "    MV_TAIL;\n"
    "}\n"
    "\n"
    "kernel void k_mv_q5_1(MV_PARAMS) {\n"
    "    MV_HEAD;\n"
    "    int nb = a.n_in / 32;\n"
    "    device const uchar *rw = wb + a.w_off + (ulong)row * nb * 24;\n"
    "    float s = 0;\n"
    "    for (int b = tiisg; b < nb; b += 32) {\n"
    "        device const uchar *blk = rw + (ulong)b * 24;\n"
    "        float d = (float)*(device const half *)blk;\n"
    "        float mm = (float)*(device const half *)(blk + 2);\n"
    "        uint qh = (uint)blk[4] | ((uint)blk[5] << 8) |\n"
    "                  ((uint)blk[6] << 16) | ((uint)blk[7] << 24);\n"
    "        device const uchar *q = blk + 8;\n"
    "        device const float *xp = x + b * 32;\n"
    "        float t = 0, sx = 0;\n"
    "        for (int j = 0; j < 16; j++) {\n"
    "            t += (float)((q[j] & 0xF) | (((qh >> j) & 1u) << 4)) * xp[j] +\n"
    "                 (float)((q[j] >> 4)  | (((qh >> (j + 16)) & 1u) << 4)) * xp[j + 16];\n"
    "            sx += xp[j] + xp[j + 16];\n"
    "        }\n"
    "        s += d * t + mm * sx;\n"
    "    }\n"
    "    MV_TAIL;\n"
    "}\n"
    "\n"
    "static inline void get_scale_min_k4(int j, device const uchar *q,\n"
    "                                    thread uchar *d, thread uchar *m) {\n"
    "    if (j < 4) {\n"
    "        *d = q[j] & 63;\n"
    "        *m = q[j + 4] & 63;\n"
    "    } else {\n"
    "        *d = (q[j + 4] & 0xF) | ((q[j - 4] >> 6) << 4);\n"
    "        *m = (q[j + 4] >> 4)  | ((q[j    ] >> 6) << 4);\n"
    "    }\n"
    "}\n"
    "\n"
    "kernel void k_mv_q4_K(MV_PARAMS) {\n"
    "    MV_HEAD;\n"
    "    int nb = a.n_in / 256;\n"
    "    device const uchar *rw = wb + a.w_off + (ulong)row * nb * 144;\n"
    "    float s = 0;\n"
    "    for (int b = tiisg; b < nb; b += 32) {\n"
    "        device const uchar *blk = rw + (ulong)b * 144;\n"
    "        float d    = (float)*(device const half *)blk;\n"
    "        float dmin = (float)*(device const half *)(blk + 2);\n"
    "        device const uchar *sc = blk + 4;\n"
    "        device const uchar *q  = blk + 16;\n"
    "        device const float *xp = x + b * 256;\n"
    "        int is = 0;\n"
    "        for (int j = 0; j < 256; j += 64) {\n"
    "            uchar s1, m1, s2, m2;\n"
    "            get_scale_min_k4(is + 0, sc, &s1, &m1);\n"
    "            get_scale_min_k4(is + 1, sc, &s2, &m2);\n"
    "            float d1 = d * s1, mm1 = dmin * m1;\n"
    "            float d2 = d * s2, mm2 = dmin * m2;\n"
    "            float t1 = 0, t2 = 0, sx1 = 0, sx2 = 0;\n"
    "            for (int l = 0; l < 32; l++) {\n"
    "                t1 += (float)(q[l] & 0xF) * xp[l];      sx1 += xp[l];\n"
    "                t2 += (float)(q[l] >> 4)  * xp[l + 32]; sx2 += xp[l + 32];\n"
    "            }\n"
    "            s += d1 * t1 - mm1 * sx1 + d2 * t2 - mm2 * sx2;\n"
    "            q += 32; is += 2; xp += 64;\n"
    "        }\n"
    "    }\n"
    "    MV_TAIL;\n"
    "}\n"
    "\n"
    "kernel void k_mv_q5_K(MV_PARAMS) {\n"
    "    MV_HEAD;\n"
    "    int nb = a.n_in / 256;\n"
    "    device const uchar *rw = wb + a.w_off + (ulong)row * nb * 176;\n"
    "    float s = 0;\n"
    "    for (int b = tiisg; b < nb; b += 32) {\n"
    "        device const uchar *blk = rw + (ulong)b * 176;\n"
    "        float d    = (float)*(device const half *)blk;\n"
    "        float dmin = (float)*(device const half *)(blk + 2);\n"
    "        device const uchar *sc = blk + 4;\n"
    "        device const uchar *qh = blk + 16;\n"
    "        device const uchar *q  = blk + 48;\n"
    "        device const float *xp = x + b * 256;\n"
    "        int is = 0;\n"
    "        uchar u1 = 1, u2 = 2;\n"
    "        for (int j = 0; j < 256; j += 64) {\n"
    "            uchar s1, m1, s2, m2;\n"
    "            get_scale_min_k4(is + 0, sc, &s1, &m1);\n"
    "            get_scale_min_k4(is + 1, sc, &s2, &m2);\n"
    "            float d1 = d * s1, mm1 = dmin * m1;\n"
    "            float d2 = d * s2, mm2 = dmin * m2;\n"
    "            for (int l = 0; l < 32; l++) {\n"
    "                s += (d1 * (float)((q[l] & 0xF) + ((qh[l] & u1) ? 16 : 0)) - mm1) * xp[l];\n"
    "                s += (d2 * (float)((q[l] >> 4)  + ((qh[l] & u2) ? 16 : 0)) - mm2) * xp[l + 32];\n"
    "            }\n"
    "            q += 32; is += 2; xp += 64; u1 <<= 2; u2 <<= 2;\n"
    "        }\n"
    "    }\n"
    "    MV_TAIL;\n"
    "}\n"
    "\n"
    "kernel void k_mv_q6_K(MV_PARAMS) {\n"
    "    MV_HEAD;\n"
    "    int nb = a.n_in / 256;\n"
    "    device const uchar *rw = wb + a.w_off + (ulong)row * nb * 210;\n"
    "    float s = 0;\n"
    "    for (int b = tiisg; b < nb; b += 32) {\n"
    "        device const uchar *blk = rw + (ulong)b * 210;\n"
    "        device const uchar *ql = blk;\n"
    "        device const uchar *qh = blk + 128;\n"
    "        device const char  *sc = (device const char *)(blk + 192);\n"
    "        float d = (float)*(device const half *)(blk + 208);\n"
    "        device const float *xp = x + b * 256;\n"
    "        for (int half_i = 0; half_i < 2; half_i++) {\n"
    "            float t[8] = {0, 0, 0, 0, 0, 0, 0, 0};\n"
    "            for (int l = 0; l < 32; l++) {\n"
    "                int is = (l / 16) & 1;\n"
    "                int q1 = (int)((ql[l]      & 0xF) | (((qh[l] >> 0) & 3) << 4)) - 32;\n"
    "                int q2 = (int)((ql[l + 32] & 0xF) | (((qh[l] >> 2) & 3) << 4)) - 32;\n"
    "                int q3 = (int)((ql[l]      >> 4)  | (((qh[l] >> 4) & 3) << 4)) - 32;\n"
    "                int q4 = (int)((ql[l + 32] >> 4)  | (((qh[l] >> 6) & 3) << 4)) - 32;\n"
    "                t[is * 4 + 0] += q1 * xp[l];\n"
    "                t[is * 4 + 1] += q2 * xp[l + 32];\n"
    "                t[is * 4 + 2] += q3 * xp[l + 64];\n"
    "                t[is * 4 + 3] += q4 * xp[l + 96];\n"
    "            }\n"
    "            s += d * (sc[0] * t[0] + sc[2] * t[1] + sc[4] * t[2] + sc[6] * t[3] +\n"
    "                      sc[1] * t[4] + sc[3] * t[5] + sc[5] * t[6] + sc[7] * t[7]);\n"
    "            ql += 64; qh += 32; sc += 8; xp += 128;\n"
    "        }\n"
    "    }\n"
    "    MV_TAIL;\n"
    "}\n"
    "\n"
    "// ---------------------------------------------------------------- rope\n"
    "\n"
    "struct rope_args {\n"
    "    int   head_dim, n_heads, half_dim, pos, neox;\n"
    "    float mscale;\n"
    "};\n"
    "\n"
    "kernel void k_rope(device float       *v  [[buffer(0)]],\n"
    "                   device const float *fr [[buffer(1)]],\n"
    "                   constant rope_args &a  [[buffer(2)]],\n"
    "                   uint2 gid [[thread_position_in_grid]]) {\n"
    "    int j = gid.x, h = gid.y;\n"
    "    if (j >= a.half_dim || h >= a.n_heads) return;\n"
    "    float ang = a.pos * fr[j];\n"
    "    float c = cos(ang) * a.mscale, s = sin(ang) * a.mscale;\n"
    "    device float *p = v + h * a.head_dim;\n"
    "    int i0 = a.neox ? j : 2 * j;\n"
    "    int i1 = a.neox ? j + a.half_dim : i0 + 1;\n"
    "    float x0 = p[i0], x1 = p[i1];\n"
    "    p[i0] = x0 * c - x1 * s;\n"
    "    p[i1] = x0 * s + x1 * c;\n"
    "}\n"
    "\n"
    "// ---------------------------------------------------------------- kv store\n"
    "\n"
    "kernel void k_store_kv(device const float *k  [[buffer(0)]],\n"
    "                       device const float *v  [[buffer(1)]],\n"
    "                       device half        *kc [[buffer(2)]],\n"
    "                       device half        *vc [[buffer(3)]],\n"
    "                       constant int       &kv_dim [[buffer(4)]],\n"
    "                       constant ulong     &off    [[buffer(5)]],\n"
    "                       uint i [[thread_position_in_grid]]) {\n"
    "    if ((int)i < kv_dim) {\n"
    "        kc[off + i] = (half)k[i];\n"
    "        vc[off + i] = (half)v[i];\n"
    "    }\n"
    "}\n"
    "\n"
    "// ---------------------------------------------------------------- attention\n"
    "// One threadgroup per head: scores -> softmax -> weighted value sum.\n"
    "\n"
    "struct attn_args {\n"
    "    int   head_dim, n_head, n_head_kv, n_ctx, pos;\n"
    "    ulong l_off;      // this layer's element offset into the kv cache\n"
    "    float scale;\n"
    "};\n"
    "\n"
    "kernel void k_attn(device const float *q   [[buffer(0)]],\n"
    "                   device const half  *kc  [[buffer(1)]],\n"
    "                   device const half  *vc  [[buffer(2)]],\n"
    "                   device float       *att [[buffer(3)]],\n"
    "                   device float       *out [[buffer(4)]],\n"
    "                   constant attn_args &a   [[buffer(5)]],\n"
    "                   uint h   [[threadgroup_position_in_grid]],\n"
    "                   uint tid [[thread_position_in_threadgroup]],\n"
    "                   uint tpg [[threads_per_threadgroup]]) {\n"
    "    threadgroup float red[256];\n"
    "    int hd = a.head_dim;\n"
    "    int kvh = h / (a.n_head / a.n_head_kv);\n"
    "    int kv_dim = a.n_head_kv * hd;\n"
    "    device const float *qh = q + h * hd;\n"
    "    device float *ah = att + (ulong)h * a.n_ctx;\n"
    "\n"
    "    for (int t = tid; t <= a.pos; t += tpg) {\n"
    "        device const half *kt = kc + a.l_off + (ulong)t * kv_dim + kvh * hd;\n"
    "        float s = 0;\n"
    "        for (int i = 0; i < hd; i++) s += qh[i] * (float)kt[i];\n"
    "        ah[t] = s * a.scale;\n"
    "    }\n"
    "    threadgroup_barrier(mem_flags::mem_device);\n"
    "\n"
    "    // max\n"
    "    float mx = -1e30f;\n"
    "    for (int t = tid; t <= a.pos; t += tpg) mx = max(mx, ah[t]);\n"
    "    red[tid] = mx;\n"
    "    threadgroup_barrier(mem_flags::mem_threadgroup);\n"
    "    for (uint off = tpg / 2; off > 0; off >>= 1) {\n"
    "        if (tid < off) red[tid] = max(red[tid], red[tid + off]);\n"
    "        threadgroup_barrier(mem_flags::mem_threadgroup);\n"
    "    }\n"
    "    mx = red[0];\n"
    "    threadgroup_barrier(mem_flags::mem_threadgroup);\n"
    "    // exp + sum\n"
    "    float sum = 0;\n"
    "    for (int t = tid; t <= a.pos; t += tpg) {\n"
    "        float e = exp(ah[t] - mx);\n"
    "        ah[t] = e;\n"
    "        sum += e;\n"
    "    }\n"
    "    red[tid] = sum;\n"
    "    threadgroup_barrier(mem_flags::mem_threadgroup);\n"
    "    for (uint off = tpg / 2; off > 0; off >>= 1) {\n"
    "        if (tid < off) red[tid] += red[tid + off];\n"
    "        threadgroup_barrier(mem_flags::mem_threadgroup);\n"
    "    }\n"
    "    sum = red[0];\n"
    "    threadgroup_barrier(mem_flags::mem_device);\n"
    "\n"
    "    for (int i = tid; i < hd; i += tpg) {\n"
    "        float o = 0;\n"
    "        for (int t = 0; t <= a.pos; t++)\n"
    "            o += ah[t] * (float)vc[a.l_off + (ulong)t * kv_dim + kvh * hd + i];\n"
    "        out[h * hd + i] = o / sum;\n"
    "    }\n"
    "}\n"
    "\n"
    "// ---------------------------------------------------------------- elementwise\n"
    "\n"
    "kernel void k_silu_mul(device float       *g [[buffer(0)]],\n"
    "                       device const float *u [[buffer(1)]],\n"
    "                       constant int       &n [[buffer(2)]],\n"
    "                       uint i [[thread_position_in_grid]]) {\n"
    "    if ((int)i < n) {\n"
    "        float x = g[i];\n"
    "        g[i] = (x / (1.0f + exp(-x))) * u[i];\n"
    "    }\n"
    "}\n"
    "\n"
    "kernel void k_add(device float       *x [[buffer(0)]],\n"
    "                  device const float *d [[buffer(1)]],\n"
    "                  constant int       &n [[buffer(2)]],\n"
    "                  uint i [[thread_position_in_grid]]) {\n"
    "    if ((int)i < n) x[i] += d[i];\n"
    "}\n"
    "\n"
;
