// JSON-Schema-constrained decoding: compile a schema into a node tree, then
// validate generated bytes incrementally so sampling can reject any token
// that would break the schema. Properties are enforced in declared order
// (required ones mandatory, optional ones skippable), matching how
// grammar-based constrained decoding behaves elsewhere.
#include "runner.h"
#include "json.h"

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <limits.h>
#include <math.h>

// ---------------------------------------------------------------- compile

static snode *sn_new(int kind) {
    snode *n = calloc(1, sizeof(snode));
    n->kind = kind;
    n->max_items = -1;
    return n;
}

void schema_free(snode *n) {
    if (!n) return;
    for (int i = 0; i < n->n_lits; i++) free(n->lits[i]);
    free(n->lits);
    for (int i = 0; i < n->n_props; i++) { free(n->keys[i]); schema_free(n->props[i]); }
    free(n->keys); free(n->key_len); free(n->props); free(n->req);
    schema_free(n->items);
    for (int i = 0; i < n->n_alts; i++) schema_free(n->alts[i]);
    free(n->alts);
    free(n);
}

static snode *compile_node(jv *s, char *err, int errcap, int depth);

static bool compile_bound(jv *v, int dflt, int *out) {
    if (!v) { *out = dflt; return true; }
    if (v->type != J_NUM || v->num < 0 || v->num > INT_MAX ||
        floor(v->num) != v->num)
        return false;
    *out = (int)v->num;
    return true;
}

static bool plain_key(const char *s) {
    for (const unsigned char *p = (const unsigned char *)s; *p; p++)
        if (*p < 0x20 || *p == '"' || *p == '\\') return false;
    return true;
}

static int prop_index(jv *props, const char *key) {
    if (!props || props->type != J_OBJ) return -1;
    for (int i = 0; i < props->n; i++)
        if (!strcmp(props->keys[i], key)) return i;
    return -1;
}

static bool same_prop_order(jv *a, jv *b) {
    if (!a || !b || a->type != J_OBJ || b->type != J_OBJ || a->n != b->n)
        return false;
    for (int i = 0; i < a->n; i++)
        if (strcmp(a->keys[i], b->keys[i]) != 0) return false;
    return true;
}

static snode *compile_discriminated_action(jv *alts, char *err, int errcap,
                                           int depth, bool *matched) {
    *matched = false;
    if (alts->n <= 0 || alts->n > 60) return NULL;

    jv *first_props = jv_get(alts->items[0], "properties");
    if (!first_props || first_props->type != J_OBJ) return NULL;
    if (first_props->n <= 0 || first_props->n > 60) return NULL;
    int tool_i = prop_index(first_props, "tool");
    int args_i = prop_index(first_props, "args");
    if (tool_i < 0 || args_i < 0) return NULL;
    if (args_i < tool_i) {
        *matched = true;
        snprintf(err, errcap, "tool discriminator must precede args");
        return NULL;
    }

    for (int a = 0; a < alts->n; a++) {
        jv *props = jv_get(alts->items[a], "properties");
        if (!same_prop_order(first_props, props)) return NULL;
        jv *cn = jv_get(props->items[tool_i], "const");
        if (!cn || (cn->type != J_STR && cn->type != J_NUM &&
                    cn->type != J_BOOL && cn->type != J_NULL))
            return NULL;
    }

    *matched = true;
    snode *n = sn_new(SN_OBJ);
    n->n_props = first_props->n;
    n->keys    = calloc(first_props->n, sizeof(char *));
    n->key_len = calloc(first_props->n, sizeof(int));
    n->props   = calloc(first_props->n, sizeof(snode *));
    n->req     = calloc(first_props->n, sizeof(bool));

    for (int i = 0; i < first_props->n; i++) {
        if (!plain_key(first_props->keys[i])) {
            snprintf(err, errcap, "property keys needing JSON escapes are unsupported");
            schema_free(n);
            return NULL;
        }
        n->keys[i] = strdup(first_props->keys[i]);
        n->key_len[i] = (int)strlen(first_props->keys[i]);
    }

    snode *tool = sn_new(SN_ENUM);
    tool->lits = calloc(alts->n, sizeof(char *));
    for (int a = 0; a < alts->n; a++) {
        jv *props = jv_get(alts->items[a], "properties");
        sbuf lit = {0};
        jv_dump(jv_get(props->items[tool_i], "const"), &lit);
        for (int prev = 0; prev < a; prev++) {
            if (!strcmp(tool->lits[prev], lit.s)) {
                free(lit.s);
                snprintf(err, errcap, "duplicate discriminator const");
                schema_free(tool);
                schema_free(n);
                return NULL;
            }
        }
        tool->lits[tool->n_lits++] = lit.s;
    }
    n->props[tool_i] = tool;

    snode *args = sn_new(SN_COND);
    args->alts = calloc(alts->n, sizeof(snode *));
    for (int a = 0; a < alts->n; a++) {
        jv *props = jv_get(alts->items[a], "properties");
        args->alts[args->n_alts] = compile_node(props->items[args_i], err, errcap,
                                                depth + 1);
        if (!args->alts[args->n_alts]) {
            schema_free(args);
            schema_free(n);
            return NULL;
        }
        args->n_alts++;
    }
    n->props[args_i] = args;

    for (int i = 0; i < first_props->n; i++) {
        if (i == tool_i || i == args_i) continue;
        n->props[i] = compile_node(first_props->items[i], err, errcap, depth + 1);
        if (!n->props[i]) { schema_free(n); return NULL; }
    }

    jv *req = jv_get(alts->items[0], "required");
    if (req && req->type == J_ARR) {
        for (int r = 0; r < req->n; r++) {
            const char *k = jv_str(req->items[r], NULL);
            bool found = false;
            for (int i = 0; i < first_props->n && k; i++)
                if (!strcmp(n->keys[i], k)) { n->req[i] = true; found = true; }
            if (!found) {
                snprintf(err, errcap, "required key '%s' not in properties",
                         k ? k : "?");
                schema_free(n);
                return NULL;
            }
        }
    }
    // the compiled object carries one required set, so every alternative
    // must declare the same one — a per-branch difference would be enforced
    // as alternative 0's rules on all branches
    for (int a = 1; a < alts->n; a++) {
        jv *other = jv_get(alts->items[a], "required");
        int rn = req && req->type == J_ARR ? req->n : 0;
        int on = other && other->type == J_ARR ? other->n : 0;
        bool same = rn == on;
        for (int r = 0; same && r < rn; r++) {
            const char *k0 = jv_str(req->items[r], NULL);
            const char *k1 = jv_str(other->items[r], NULL);
            same = k0 && k1 && !strcmp(k0, k1);
        }
        if (!same) {
            snprintf(err, errcap, "oneOf alternatives declare different required keys");
            schema_free(n);
            return NULL;
        }
    }
    return n;
}

static snode *compile_typed(jv *s, const char *type, char *err, int errcap, int depth) {
    if (!strcmp(type, "string")) {
        snode *n = sn_new(SN_STR);
        jv *mn = jv_get(s, "minLength"), *mx = jv_get(s, "maxLength");
        if (!compile_bound(mn, 0, &n->min_items) ||
            !compile_bound(mx, -1, &n->max_items) ||
            (n->max_items >= 0 && n->min_items > n->max_items)) {
            snprintf(err, errcap, "invalid string length bounds");
            schema_free(n);
            return NULL;
        }
        return n;
    }
    if (!strcmp(type, "number"))  return sn_new(SN_NUM);
    if (!strcmp(type, "integer")) return sn_new(SN_INT);
    if (!strcmp(type, "boolean")) return sn_new(SN_BOOL);
    if (!strcmp(type, "null"))    return sn_new(SN_NULL);
    if (!strcmp(type, "array")) {
        snode *n = sn_new(SN_ARR);
        n->items = compile_node(jv_get(s, "items"), err, errcap, depth + 1);
        if (!n->items) { schema_free(n); return NULL; }
        jv *mi = jv_get(s, "minItems"), *ma = jv_get(s, "maxItems");
        if (!compile_bound(mi, 0, &n->min_items) ||
            !compile_bound(ma, -1, &n->max_items) ||
            (n->max_items >= 0 && n->min_items > n->max_items)) {
            snprintf(err, errcap, "invalid array item bounds");
            schema_free(n);
            return NULL;
        }
        return n;
    }
    if (!strcmp(type, "object")) {
        jv *props = jv_get(s, "properties");
        if (!props || props->type != J_OBJ || props->n == 0) {
            // open object: any JSON object (generic machine, '{' enforced)
            snode *n = sn_new(SN_ANY);
            n->min_items = 1; // flag: object-rooted generic value
            return n;
        }
        if (props->n > 60) {
            snprintf(err, errcap, "too many properties (max 60)");
            return NULL;
        }
        snode *n = sn_new(SN_OBJ);
        n->n_props = props->n;
        n->keys    = calloc(props->n, sizeof(char *));
        n->key_len = calloc(props->n, sizeof(int));
        n->props   = calloc(props->n, sizeof(snode *));
        n->req     = calloc(props->n, sizeof(bool));
        for (int i = 0; i < props->n; i++) {
            if (!plain_key(props->keys[i])) {
                snprintf(err, errcap, "property keys needing JSON escapes are unsupported");
                schema_free(n);
                return NULL;
            }
            n->keys[i] = strdup(props->keys[i]);
            n->key_len[i] = (int)strlen(props->keys[i]);
            n->props[i] = compile_node(props->items[i], err, errcap, depth + 1);
            if (!n->props[i]) { schema_free(n); return NULL; }
        }
        jv *req = jv_get(s, "required");
        if (req && req->type == J_ARR) {
            for (int r = 0; r < req->n; r++) {
                const char *k = jv_str(req->items[r], NULL);
                bool found = false;
                for (int i = 0; i < props->n && k; i++)
                    if (!strcmp(n->keys[i], k)) { n->req[i] = true; found = true; }
                if (!found) {
                    snprintf(err, errcap, "required key '%s' not in properties",
                             k ? k : "?");
                    schema_free(n);
                    return NULL;
                }
            }
        }
        return n;
    }
    snprintf(err, errcap, "unsupported type '%s'", type);
    return NULL;
}

// first bytes that can start a value of node `a`; false when the node cannot
// be dispatched by first byte at all (nested unions/conditionals, open any)
static bool union_start_bytes(const snode *a, bool set[256]) {
    switch (a->kind) {
        case SN_STR: set['"'] = true; return true;
        case SN_ENUM:
            for (int i = 0; i < a->n_lits; i++)
                set[(uint8_t)a->lits[i][0]] = true;
            return true;
        case SN_OBJ: set['{'] = true; return true;
        case SN_ARR: set['['] = true; return true;
        case SN_BOOL: set['t'] = true; set['f'] = true; return true;
        case SN_NULL: set['n'] = true; return true;
        case SN_NUM: case SN_INT:
            set['-'] = true;
            for (int d = '0'; d <= '9'; d++) set[d] = true;
            return true;
        default: return false;
    }
}

static snode *compile_oneof(jv *alts, char *err, int errcap, int depth) {
    if (!alts || alts->type != J_ARR || alts->n <= 0) {
        snprintf(err, errcap, "oneOf/anyOf must be a non-empty array");
        return NULL;
    }
    bool all_scalar_const = true;
    for (int i = 0; i < alts->n; i++) {
        jv *cn = jv_get(alts->items[i], "const");
        if (!cn || (cn->type != J_STR && cn->type != J_NUM &&
                    cn->type != J_BOOL && cn->type != J_NULL)) {
            all_scalar_const = false;
            break;
        }
    }
    if (all_scalar_const) {
        if (alts->n <= 0 || alts->n > 60) {
            snprintf(err, errcap, "enum size must be 1..60");
            return NULL;
        }
        snode *n = sn_new(SN_ENUM);
        n->lits = calloc(alts->n, sizeof(char *));
        for (int i = 0; i < alts->n; i++) {
            sbuf lit = {0};
            jv_dump(jv_get(alts->items[i], "const"), &lit);
            n->lits[i] = lit.s;
            n->n_lits++;
        }
        return n;
    }

    bool matched = false;
    snode *disc = compile_discriminated_action(alts, err, errcap, depth, &matched);
    if (matched) return disc;

    snode *n = sn_new(SN_UNION);
    n->alts = calloc(alts->n, sizeof(snode *));
    for (int i = 0; i < alts->n; i++) {
        n->alts[n->n_alts] = compile_node(alts->items[i], err, errcap, depth + 1);
        if (!n->alts[n->n_alts]) { schema_free(n); return NULL; }
        n->n_alts++;
    }
    // the validator dispatches a union on the first byte of the value —
    // alternatives it could never select must fail here, at request time,
    // not silently mis-constrain sampling later
    if (n->n_alts > 1) {
        bool seen[256] = { false };
        for (int i = 0; i < n->n_alts; i++) {
            bool mine[256] = { false };
            if (!union_start_bytes(n->alts[i], mine)) {
                snprintf(err, errcap,
                         "oneOf alternative %d cannot be dispatched by its first byte", i);
                schema_free(n);
                return NULL;
            }
            for (int b = 0; b < 256; b++) {
                if (mine[b] && seen[b]) {
                    snprintf(err, errcap,
                             "oneOf alternatives are ambiguous (share a starting byte)");
                    schema_free(n);
                    return NULL;
                }
                if (mine[b]) seen[b] = true;
            }
        }
    }
    return n;
}

static snode *compile_node(jv *s, char *err, int errcap, int depth) {
    if (depth > 24) { snprintf(err, errcap, "schema too deep"); return NULL; }
    if (!s || s->type == J_NULL || (s->type == J_OBJ && s->n == 0) ||
        s->type == J_BOOL) // `true` / `{}` = anything
        return sn_new(SN_ANY);
    if (s->type != J_OBJ) { snprintf(err, errcap, "schema node must be an object"); return NULL; }

    jv *one = jv_get(s, "oneOf");
    jv *any = jv_get(s, "anyOf");
    if (one || any) return compile_oneof(one ? one : any, err, errcap, depth);

    // enum / const dominate the type
    jv *en = jv_get(s, "enum");
    jv *cn = jv_get(s, "const");
    if (en || cn) {
        snode *n = sn_new(SN_ENUM);
        int cnt = en ? en->n : 1;
        if (cnt <= 0 || cnt > 60) {
            snprintf(err, errcap, "enum size must be 1..60");
            schema_free(n);
            return NULL;
        }
        n->lits = calloc(cnt, sizeof(char *));
        for (int i = 0; i < cnt; i++) {
            jv *v = en ? en->items[i] : cn;
            if (v->type != J_STR && v->type != J_NUM &&
                v->type != J_BOOL && v->type != J_NULL) {
                snprintf(err, errcap, "enum values must be scalars");
                schema_free(n);
                return NULL;
            }
            sbuf lit = {0};
            jv_dump(v, &lit);
            n->lits[i] = lit.s;
            n->n_lits++;
        }
        return n;
    }

    jv *ty = jv_get(s, "type");
    if (!ty) {
        if (jv_get(s, "properties")) return compile_typed(s, "object", err, errcap, depth);
        if (jv_get(s, "items"))      return compile_typed(s, "array", err, errcap, depth);
        return sn_new(SN_ANY);
    }
    if (ty->type == J_STR) return compile_typed(s, ty->str, err, errcap, depth);
    if (ty->type == J_ARR) { // union, e.g. ["string","null"]
        // An empty list compiles to a union with no alternatives, which every
        // consumer treats as "at least one exists": pick_alt matches nothing so
        // sampling stalls, and the forced-completion path then reads alts[0]
        // out of a zero-byte allocation. Reject it at compile time.
        if (ty->n <= 0) {
            snprintf(err, errcap, "'type' array must list at least one type");
            return NULL;
        }
        snode *n = sn_new(SN_UNION);
        n->alts = calloc(ty->n, sizeof(snode *));
        bool has_num = false;
        for (int i = 0; i < ty->n; i++) {
            const char *t = jv_str(ty->items[i], "?");
            if ((!strcmp(t, "number") || !strcmp(t, "integer"))) {
                if (has_num) continue; // merge number|integer
                has_num = true;
                t = strcmp(t, "integer") == 0 && ty->n == 1 ? "integer" : "number";
            }
            snode *alt = compile_typed(s, t, err, errcap, depth + 1);
            if (!alt) { schema_free(n); return NULL; }
            n->alts[n->n_alts++] = alt;
        }
        return n;
    }
    snprintf(err, errcap, "bad 'type' value");
    return NULL;
}

snode *schema_compile(struct jv *schema, char *err, int errcap) {
    err[0] = 0;
    return compile_node(schema, err, errcap, 0);
}

// ---------------------------------------------------------------- validate

// frame phases
enum {
    P_START,          // value not begun
    P_OBJ_KEY1,       // after '{': key or '}'
    P_OBJ_KEY,        // after ',': key
    P_OBJ_INKEY,      // inside key string
    P_OBJ_COLON,
    P_OBJ_NEXT,       // after value: ',' or '}'
    P_ARR_FIRST,      // after '[': value or ']'
    P_ARR_NEXT,       // after item: ',' or ']'
    P_STR,            // inside string
    P_LIT,            // enum / bool / null literal
    P_NUM,
};

// number micro-states (frame->sub)
enum { N_START, N_MINUS, N_ZERO, N_INT, N_FRAC0, N_FRAC, N_EXP0, N_EXP1, N_EXP };

static bool is_ws(uint8_t c) {
    return c == ' ' || c == '\t' || c == '\n' || c == '\r';
}

void sval_init(sval *v, const snode *root) {
    memset(v, 0, sizeof(*v));
    v->stack[0] = (sframe){ .node = root, .phase = P_START };
    v->depth = 1;
    v->last_enum = -1;
}

// discriminator choice for the frame at stack index `at`: an SN_COND frame
// reads its owning object (the frame below), everything else its own record
static int frame_choice(const sval *v, int at) {
    const sframe *f = &v->stack[at];
    if (f->node->kind == SN_COND)
        return at > 0 ? (int)v->stack[at - 1].disc - 1 : -1;
    return (int)f->disc - 1;
}

// key candidates from prop index `from`: every prop until (and including)
// the first required one may come next
static uint64_t key_candidates(const snode *n, int from) {
    uint64_t m = 0;
    for (int i = from; i < n->n_props; i++) {
        m |= 1ull << i;
        if (n->req[i]) break;
    }
    return m;
}

static bool close_allowed(const snode *n, int from) {
    for (int i = from; i < n->n_props; i++)
        if (n->req[i]) return false;
    return true;
}

static void frame_done(sval *v);

// child value finished: advance parent
static void frame_done(sval *v) {
    v->depth--;
    if (v->depth == 0) { v->done = true; return; }
    sframe *f = &v->stack[v->depth - 1];
    if (f->node->kind == SN_OBJ) {
        if (f->sub < f->node->n_props && v->last_enum >= 0 &&
            !strcmp(f->node->keys[f->sub], "tool"))
            f->disc = (uint16_t)(v->last_enum + 1);
        f->phase = P_OBJ_NEXT;
    } else {
        f->phase = P_ARR_NEXT; // SN_ARR
    }
}

// begin a value of type `n` on top of the stack (replaces union in place)
static bool push_value(sval *v, const snode *n) {
    if (v->depth >= (int)(sizeof(v->stack) / sizeof(v->stack[0]))) return false;
    v->last_enum = -1;
    v->stack[v->depth++] = (sframe){ .node = n, .phase = P_START };
    return true;
}

// which union alternative starts with byte c?
static const snode *pick_alt(const snode *u, uint8_t c) {
    for (int i = 0; i < u->n_alts; i++) {
        const snode *a = u->alts[i];
        switch (a->kind) {
            case SN_STR:  if (c == '"') return a; break;
            case SN_ENUM:
                for (int j = 0; j < a->n_lits; j++)
                    if (c == a->lits[j][0]) return a;
                break;
            case SN_OBJ:  if (c == '{') return a; break;
            case SN_ARR:  if (c == '[') return a; break;
            case SN_BOOL: if (c == 't' || c == 'f') return a; break;
            case SN_NULL: if (c == 'n') return a; break;
            case SN_NUM: case SN_INT:
                if (c == '-' || (c >= '0' && c <= '9')) return a;
                break;
            case SN_ANY:  return a;
            default: break;
        }
    }
    return NULL;
}

// string content byte (frame->sub tracks escapes); returns -1 invalid,
// 0 continue, 1 string closed
static int str_byte(uint8_t c, uint8_t *sub) {
    if (*sub == 1) { // after backslash
        if (c == '"' || c == '\\' || c == '/' || c == 'b' || c == 'f' ||
            c == 'n' || c == 'r' || c == 't') { *sub = 0; return 0; }
        if (c == 'u') { *sub = 2; return 0; }
        return -1;
    }
    if (*sub >= 2) { // \uXXXX
        if ((c >= '0' && c <= '9') || (c >= 'a' && c <= 'f') ||
            (c >= 'A' && c <= 'F')) {
            *sub = *sub == 5 ? 0 : *sub + 1;
            return 0;
        }
        return -1;
    }
    if (c == '"') return 1;
    if (c == '\\') { *sub = 1; return 0; }
    return c >= 0x20 ? 0 : -1;
}

// number byte; returns -1 invalid, 0 consumed, 1 complete-and-reconsume
static int num_byte(uint8_t c, uint8_t *st, bool integer) {
    switch (*st) {
        case N_START:
            if (c == '-') { *st = N_MINUS; return 0; }
            if (c == '0') { *st = N_ZERO; return 0; }
            if (c >= '1' && c <= '9') { *st = N_INT; return 0; }
            return -1;
        case N_MINUS:
            if (c == '0') { *st = N_ZERO; return 0; }
            if (c >= '1' && c <= '9') { *st = N_INT; return 0; }
            return -1;
        case N_ZERO:
        case N_INT:
            if (*st == N_INT && c >= '0' && c <= '9') return 0;
            if (!integer && c == '.') { *st = N_FRAC0; return 0; }
            if (!integer && (c == 'e' || c == 'E')) { *st = N_EXP0; return 0; }
            return 1;
        case N_FRAC0:
            if (c >= '0' && c <= '9') { *st = N_FRAC; return 0; }
            return -1;
        case N_FRAC:
            if (c >= '0' && c <= '9') return 0;
            if (c == 'e' || c == 'E') { *st = N_EXP0; return 0; }
            return 1;
        case N_EXP0:
            if (c == '+' || c == '-') { *st = N_EXP1; return 0; }
            if (c >= '0' && c <= '9') { *st = N_EXP; return 0; }
            return -1;
        case N_EXP1:
            if (c >= '0' && c <= '9') { *st = N_EXP; return 0; }
            return -1;
        case N_EXP:
            if (c >= '0' && c <= '9') return 0;
            return 1;
    }
    return -1;
}

static bool num_complete(uint8_t st) {
    return st == N_ZERO || st == N_INT || st == N_FRAC || st == N_EXP;
}

// feed one byte; returns -1 invalid, 0 consumed, 1 reconsume (frame popped)
static int feed_byte(sval *v, uint8_t c) {
    if (v->done) return -1; // nothing after the root value
    sframe *f = &v->stack[v->depth - 1];
    const snode *n = f->node;

    // generic any-value subtree
    if (n->kind == SN_ANY) {
        if (f->phase == P_START) {
            if (is_ws(c)) return 0;
            if (n->min_items) jsonv_init(&v->any);      // object-rooted
            else              jsonv_init_any(&v->any);  // any value
            f->phase = P_STR; // "running"
        }
        if (v->any.done) { frame_done(v); return 1; }
        if (jsonv_feed(&v->any, (const char *)&c, 1)) {
            if (v->any.done) frame_done(v);
            return 0;
        }
        // invalid for the submachine: if it stopped at a self-terminating
        // value end (number at top level), the byte belongs to our parent
        if (jsonv_value_end(&v->any)) { frame_done(v); return 1; }
        return -1;
    }

    switch (f->phase) {
    case P_START:
        if (is_ws(c)) return 0;
        switch (n->kind) {
        case SN_COND: {
            int choice = frame_choice(v, v->depth - 1);
            if (choice < 0 || choice >= n->n_alts) return -1;
            v->stack[v->depth - 1].node = n->alts[choice];
            return feed_byte(v, c);
        }
        case SN_UNION: {
            const snode *alt = pick_alt(n, c);
            if (!alt) return -1;
            v->stack[v->depth - 1].node = alt; // resolve in place
            return feed_byte(v, c);
        }
        case SN_STR:
            if (c != '"') return -1;
            f->phase = P_STR; f->sub = 0; f->lit_pos = 0;
            return 0;
        case SN_ENUM:
        case SN_BOOL:
        case SN_NULL:
            f->phase = P_LIT;
            f->lit_pos = 0;
            f->sub = 0;
            if (n->kind == SN_ENUM) {
                f->alive = (n->n_lits >= 64 ? ~0ull : (1ull << n->n_lits) - 1);
            } else {
                f->alive = n->kind == SN_BOOL ? 3 : 1; // true/false or null
            }
            return feed_byte(v, c) == -1 ? -1 : 0;
        case SN_NUM:
        case SN_INT:
            f->phase = P_NUM; f->sub = N_START;
            return num_byte(c, &f->sub, n->kind == SN_INT) == 0 ? 0 : -1;
        case SN_OBJ:
            if (c != '{') return -1;
            f->phase = P_OBJ_KEY1; f->idx = 0;
            return 0;
        case SN_ARR:
            if (c != '[') return -1;
            f->phase = P_ARR_FIRST; f->idx = 0;
            return 0;
        default:
            return -1;
        }

    case P_STR: {
        // a full string at maxLength admits only the closing quote — reject an
        // escape opener up front so a close() can never overrun the bound
        if (f->sub == 0 && c == '\\' &&
            n->max_items >= 0 && f->lit_pos >= n->max_items)
            return -1;
        int r = str_byte(c, &f->sub);
        if (r < 0) return -1;
        if (r == 1) {
            if (f->lit_pos < n->min_items ||
                (n->max_items >= 0 && f->lit_pos > n->max_items))
                return -1;
            frame_done(v);
        } else if (f->sub == 0) {
            f->lit_pos++;
            if (n->max_items >= 0 && f->lit_pos > n->max_items)
                return -1;
        }
        return 0;
    }

    case P_LIT: {
        // match against alive literal candidates
        static const char *bools[] = { "true", "false" };
        static const char *nulls[] = { "null" };
        const char *const *lits = n->kind == SN_ENUM ? (const char *const *)n->lits :
                                  n->kind == SN_BOOL ? bools : nulls;
        int cnt = n->kind == SN_ENUM ? n->n_lits : (n->kind == SN_BOOL ? 2 : 1);
        uint64_t next = 0;
        int completed = -1;
        int pending_completed = f->sub ? f->sub - 1 : -1;
        for (int i = 0; i < cnt; i++) {
            if (!(f->alive & (1ull << i))) continue;
            const char *L = lits[i];
            if (L[f->lit_pos] != (char)c) continue;
            if (L[f->lit_pos + 1] == 0) completed = i;
            else next |= 1ull << i;
        }
        if (completed >= 0 && next == 0) {
            if (n->kind == SN_ENUM) v->last_enum = completed;
            frame_done(v);
            return 0;
        }
        if (!next) {
            if (pending_completed >= 0) {
                if (n->kind == SN_ENUM) v->last_enum = pending_completed;
                frame_done(v);
                return 1;
            }
            return -1;
        }
        f->alive = next;
        f->sub = completed >= 0 ? (uint8_t)(completed + 1) : 0;
        f->lit_pos++;
        return 0;
    }

    case P_NUM: {
        int r = num_byte(c, &f->sub, n->kind == SN_INT);
        if (r < 0) return -1;
        if (r == 1) { frame_done(v); return 1; }
        return 0;
    }

    case P_OBJ_KEY1:
    case P_OBJ_KEY:
        if (is_ws(c)) return 0;
        if (c == '}' && f->phase == P_OBJ_KEY1) {
            if (!close_allowed(n, f->idx)) return -1;
            frame_done(v);
            return 0;
        }
        if (c != '"') return -1;
        f->alive = key_candidates(n, f->idx);
        if (!f->alive) return -1;
        f->phase = P_OBJ_INKEY;
        f->lit_pos = 0;
        return 0;

    case P_OBJ_INKEY: {
        if (c == '"') {
            // exactly one candidate must match to full length
            for (int i = 0; i < n->n_props; i++) {
                if ((f->alive & (1ull << i)) && n->key_len[i] == f->lit_pos) {
                    f->idx = i + 1;
                    f->sub = i; // remember which prop for the value
                    f->phase = P_OBJ_COLON;
                    return 0;
                }
            }
            return -1;
        }
        uint64_t next = 0;
        for (int i = 0; i < n->n_props; i++)
            if ((f->alive & (1ull << i)) && f->lit_pos < n->key_len[i] &&
                n->keys[i][f->lit_pos] == (char)c)
                next |= 1ull << i;
        if (!next) return -1;
        f->alive = next;
        f->lit_pos++;
        return 0;
    }

    case P_OBJ_COLON:
        if (is_ws(c)) return 0;
        if (c != ':') return -1;
        f->phase = P_OBJ_NEXT; // resumed here after the child completes
        return push_value(v, n->props[f->sub]) ? 0 : -1;

    case P_OBJ_NEXT:
        if (is_ws(c)) return 0;
        if (c == ',') {
            if (f->idx >= n->n_props || !key_candidates(n, f->idx)) return -1;
            f->phase = P_OBJ_KEY;
            return 0;
        }
        if (c == '}') {
            if (!close_allowed(n, f->idx)) return -1;
            frame_done(v);
            return 0;
        }
        return -1;

    case P_ARR_FIRST:
        if (is_ws(c)) return 0;
        if (c == ']') {
            if (n->min_items > 0) return -1;
            frame_done(v);
            return 0;
        }
        f->idx = 1;
        f->phase = P_ARR_NEXT;
        if (!push_value(v, n->items)) return -1;
        return feed_byte(v, c);

    case P_ARR_NEXT:
        if (is_ws(c)) return 0;
        if (c == ',') {
            if (n->max_items >= 0 && f->idx >= n->max_items) return -1;
            f->idx++;
            return push_value(v, n->items) ? 0 : -1;
        }
        if (c == ']') {
            if (f->idx < n->min_items) return -1;
            frame_done(v);
            return 0;
        }
        return -1;
    }
    return -1;
}

bool sval_feed(sval *v, const char *s, int len) {
    for (int i = 0; i < len; i++) {
        int r = feed_byte(v, (uint8_t)s[i]);
        if (r < 0) return false;
        if (r == 1) { // reconsume in parent
            r = feed_byte(v, (uint8_t)s[i]);
            if (r < 0) return false;
            if (r == 1) return false; // double reconsume: shouldn't happen
        }
    }
    return true;
}

// ---------------------------------------------------------------- close

typedef struct { char *out; int cap, n; } emitq;

static void eq_put(emitq *q, const char *s) {
    while (*s && q->n < q->cap - 1) q->out[q->n++] = *s++;
}
static void eq_putc(emitq *q, char c) {
    if (q->n < q->cap - 1) q->out[q->n++] = c;
}
// Once the buffer is full nothing further can be emitted, so the minItems /
// minLength loops below stop there. Without this they still iterate to the
// declared bound, and minItems:2000000000 (nested, worse) spins for minutes
// while a slot is held.
static bool eq_full(const emitq *q) { return q->n >= q->cap - 1; }

// minimal complete value for a schema node
static void emit_min_choice(emitq *q, const snode *n, int depth, int choice) {
    if (depth > 24) { eq_put(q, "null"); return; }
    if (n->kind == SN_COND) {
        const snode *alt = (choice >= 0 && choice < n->n_alts) ?
                           n->alts[choice] : n->alts[0];
        emit_min_choice(q, alt, depth + 1, choice);
        return;
    }
    switch (n->kind) {
        case SN_ANY:  eq_put(q, n->min_items ? "{}" : "null"); break;
        case SN_NULL: eq_put(q, "null"); break;
        case SN_BOOL: eq_put(q, "false"); break;
        case SN_NUM: case SN_INT: eq_putc(q, '0'); break;
        case SN_STR:
            eq_putc(q, '"');
            for (int i = 0; i < n->min_items && !eq_full(q); i++) eq_putc(q, ' ');
            eq_putc(q, '"');
            break;
        case SN_ENUM: eq_put(q, n->lits[0]); break;
        case SN_UNION: {
            for (int i = 0; i < n->n_alts; i++)
                if (n->alts[i]->kind == SN_NULL) { eq_put(q, "null"); return; }
            emit_min_choice(q, n->alts[0], depth + 1, choice);
            break;
        }
        case SN_ARR:
            eq_putc(q, '[');
            for (int i = 0; i < n->min_items && !eq_full(q); i++) {
                if (i) eq_putc(q, ',');
                emit_min_choice(q, n->items, depth + 1, choice);
            }
            eq_putc(q, ']');
            break;
        case SN_OBJ: {
            eq_putc(q, '{');
            bool first = true;
            for (int i = 0; i < n->n_props; i++) {
                if (!n->req[i]) continue;
                if (!first) eq_putc(q, ',');
                first = false;
                eq_putc(q, '"'); eq_put(q, n->keys[i]); eq_put(q, "\":");
                // a fresh object emits its own discriminator as lits[0], so
                // any SN_COND inside must follow alternative 0, not `choice`
                emit_min_choice(q, n->props[i], depth + 1, 0);
            }
            eq_putc(q, '}');
            break;
        }
        case SN_COND:
            break;
    }
}

// emit the remaining required properties of an object frame and close it.
// need_comma: a ',' must precede the first emitted property.
// force_one: at least one property must be emitted (a ',' was already
// consumed, so a bare '}' would be invalid JSON).
static void close_obj(emitq *q, const snode *n, int from, bool need_comma,
                      bool force_one, int choice) {
    bool emitted = false;
    for (int i = from; i < n->n_props; i++) {
        if (!n->req[i]) continue;
        if (need_comma) eq_putc(q, ',');
        need_comma = true;
        emitted = true;
        eq_putc(q, '"'); eq_put(q, n->keys[i]); eq_put(q, "\":");
        emit_min_choice(q, n->props[i], 0, choice);
    }
    if (force_one && !emitted && from < n->n_props) {
        eq_putc(q, '"'); eq_put(q, n->keys[from]); eq_put(q, "\":");
        emit_min_choice(q, n->props[from], 0, choice);
    }
    eq_putc(q, '}');
}

int sval_close(sval *v, char *out, int cap) {
    emitq q = { out, cap, 0 };
    if (v->done) { out[0] = 0; return 0; }
    // nothing generated at all: emit a full minimal document
    if (v->depth == 1 && v->stack[0].phase == P_START &&
        v->stack[0].node->kind != SN_ANY) {
        emit_min_choice(&q, v->stack[0].node, 0, -1);
        out[q.n] = 0;
        return q.n;
    }
    while (v->depth > 0) {
        sframe *f = &v->stack[v->depth - 1];
        const snode *n = f->node;
        int choice = frame_choice(v, v->depth - 1);
        switch (n->kind == SN_ANY ? P_STR + 100 : f->phase) {
        case P_STR + 100: { // any-subtree: let the generic machine close
            if (f->phase == P_START) { emit_min_choice(&q, n, 0, -1); break; }
            char tmp[512];
            int cn = jsonv_close(&v->any, tmp, sizeof(tmp));
            if (cn > 0) eq_put(&q, tmp);
            else if (!v->any.done) eq_put(&q, n->min_items ? "{}" : "null");
            break;
        }
        case P_START:
            emit_min_choice(&q, n, 0, choice);
            break;
        case P_STR:
            if (f->sub == 1) eq_putc(&q, 'n');           // dangling backslash
            while (f->sub >= 2) { eq_putc(&q, '0');       // partial \uXXXX
                                  f->sub = f->sub == 5 ? 0 : f->sub + 1; }
            while (f->lit_pos < n->min_items && !eq_full(&q)) {
                eq_putc(&q, ' ');
                f->lit_pos++;
            }
            eq_putc(&q, '"');
            break;
        case P_LIT: {
            static const char *bools[] = { "true", "false" };
            static const char *nulls[] = { "null" };
            const char *const *lits = n->kind == SN_ENUM ? (const char *const *)n->lits :
                                      n->kind == SN_BOOL ? bools : nulls;
            int cnt = n->kind == SN_ENUM ? n->n_lits : (n->kind == SN_BOOL ? 2 : 1);
            int pick = -1;
            if (n->kind == SN_ENUM && f->sub) {
                pick = f->sub - 1;
            } else {
                for (int i = 0; i < cnt; i++)
                    if (f->alive & (1ull << i)) { pick = i; break; }
            }
            if (pick < 0) break;
            eq_put(&q, lits[pick] + f->lit_pos);
            // finishing a discriminator literal decides the parent's choice —
            // the args emitted next must come from the same alternative
            if (n->kind == SN_ENUM && v->depth >= 2) {
                sframe *pf = &v->stack[v->depth - 2];
                if (pf->node->kind == SN_OBJ && pf->sub < pf->node->n_props &&
                    !strcmp(pf->node->keys[pf->sub], "tool"))
                    pf->disc = (uint16_t)(pick + 1);
            }
            break;
        }
        case P_NUM:
            if (!num_complete(f->sub)) eq_putc(&q, '0');
            break;
        case P_OBJ_KEY1:
            close_obj(&q, n, f->idx, false, false, choice);
            break;
        case P_OBJ_KEY: // a ',' was already consumed
            close_obj(&q, n, f->idx, false, true, choice);
            break;
        case P_OBJ_INKEY: {
            // finish the lowest still-alive candidate key, give it a value
            for (int i = 0; i < n->n_props; i++) {
                if (!(f->alive & (1ull << i))) continue;
                eq_put(&q, n->keys[i] + f->lit_pos);
                eq_put(&q, "\":");
                emit_min_choice(&q, n->props[i], 0, choice);
                f->idx = i + 1;
                break;
            }
            close_obj(&q, n, f->idx, true, false, choice);
            break;
        }
        case P_OBJ_COLON:
            eq_putc(&q, ':');
            emit_min_choice(&q, n->props[f->sub], 0, choice);
            close_obj(&q, n, f->idx, true, false, choice);
            break;
        case P_OBJ_NEXT: // a value just completed, comma needed before more
            close_obj(&q, n, f->idx, true, false, choice);
            break;
        case P_ARR_FIRST:
        case P_ARR_NEXT:
            for (int i = f->idx; i < n->min_items && !eq_full(&q); i++) {
                if (i > 0 || f->phase == P_ARR_NEXT) eq_putc(&q, ',');
                emit_min_choice(&q, n->items, 0, -1);
            }
            eq_putc(&q, ']');
            break;
        }
        v->depth--;
    }
    v->done = true;
    out[q.n] = 0;
    return q.n;
}
