// JSON-Schema-constrained decoding: compile a schema into a node tree, then
// validate generated bytes incrementally so sampling can reject any token
// that would break the schema. Properties are enforced in declared order
// (required ones mandatory, optional ones skippable), matching how
// grammar-based constrained decoding behaves elsewhere.
#include "runner.h"
#include "json.h"

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

// ---------------------------------------------------------------- compile

static snode *sn_new(int kind) {
    snode *n = calloc(1, sizeof(snode));
    n->kind = kind;
    n->max_items = -1;
    return n;
}

void schema_free(snode *n) {
    if (!n) return;
    for (int i = 0; i < n->n_lits; i++) free(n->lits[i]);
    free(n->lits);
    for (int i = 0; i < n->n_props; i++) { free(n->keys[i]); schema_free(n->props[i]); }
    free(n->keys); free(n->key_len); free(n->props); free(n->req);
    schema_free(n->items);
    for (int i = 0; i < n->n_alts; i++) schema_free(n->alts[i]);
    free(n->alts);
    free(n);
}

static snode *compile_node(jv *s, char *err, int errcap, int depth);

static bool plain_key(const char *s) {
    for (const unsigned char *p = (const unsigned char *)s; *p; p++)
        if (*p < 0x20 || *p == '"' || *p == '\\') return false;
    return true;
}

static snode *compile_typed(jv *s, const char *type, char *err, int errcap, int depth) {
    if (!strcmp(type, "string"))  return sn_new(SN_STR);
    if (!strcmp(type, "number"))  return sn_new(SN_NUM);
    if (!strcmp(type, "integer")) return sn_new(SN_INT);
    if (!strcmp(type, "boolean")) return sn_new(SN_BOOL);
    if (!strcmp(type, "null"))    return sn_new(SN_NULL);
    if (!strcmp(type, "array")) {
        snode *n = sn_new(SN_ARR);
        n->items = compile_node(jv_get(s, "items"), err, errcap, depth + 1);
        if (!n->items) { schema_free(n); return NULL; }
        jv *mi = jv_get(s, "minItems"), *ma = jv_get(s, "maxItems");
        n->min_items = mi ? (int)jv_num(mi, 0) : 0;
        n->max_items = ma ? (int)jv_num(ma, -1) : -1;
        if (n->min_items < 0 || n->max_items < -1 ||
            (n->max_items >= 0 && n->min_items > n->max_items)) {
            snprintf(err, errcap, "invalid array item bounds");
            schema_free(n);
            return NULL;
        }
        return n;
    }
    if (!strcmp(type, "object")) {
        jv *props = jv_get(s, "properties");
        if (!props || props->type != J_OBJ || props->n == 0) {
            // open object: any JSON object (generic machine, '{' enforced)
            snode *n = sn_new(SN_ANY);
            n->min_items = 1; // flag: object-rooted generic value
            return n;
        }
        snode *n = sn_new(SN_OBJ);
        n->n_props = props->n;
        n->keys    = calloc(props->n, sizeof(char *));
        n->key_len = calloc(props->n, sizeof(int));
        n->props   = calloc(props->n, sizeof(snode *));
        n->req     = calloc(props->n, sizeof(bool));
        for (int i = 0; i < props->n; i++) {
            if (!plain_key(props->keys[i])) {
                snprintf(err, errcap, "property keys needing JSON escapes are unsupported");
                schema_free(n);
                return NULL;
            }
            n->keys[i] = strdup(props->keys[i]);
            n->key_len[i] = (int)strlen(props->keys[i]);
            n->props[i] = compile_node(props->items[i], err, errcap, depth + 1);
            if (!n->props[i]) { schema_free(n); return NULL; }
        }
        jv *req = jv_get(s, "required");
        if (req && req->type == J_ARR) {
            for (int r = 0; r < req->n; r++) {
                const char *k = jv_str(req->items[r], NULL);
                bool found = false;
                for (int i = 0; i < props->n && k; i++)
                    if (!strcmp(n->keys[i], k)) { n->req[i] = true; found = true; }
                if (!found) {
                    snprintf(err, errcap, "required key '%s' not in properties",
                             k ? k : "?");
                    schema_free(n);
                    return NULL;
                }
            }
        }
        if (n->n_props > 60) {
            snprintf(err, errcap, "too many properties (max 60)");
            schema_free(n);
            return NULL;
        }
        return n;
    }
    snprintf(err, errcap, "unsupported type '%s'", type);
    return NULL;
}

static snode *compile_oneof(jv *alts, char *err, int errcap, int depth) {
    if (!alts || alts->type != J_ARR || alts->n == 0) {
        snprintf(err, errcap, "oneOf/anyOf must be a non-empty array");
        return NULL;
    }
    bool all_scalar_const = true;
    for (int i = 0; i < alts->n; i++) {
        jv *cn = jv_get(alts->items[i], "const");
        if (!cn || (cn->type != J_STR && cn->type != J_NUM &&
                    cn->type != J_BOOL && cn->type != J_NULL)) {
            all_scalar_const = false;
            break;
        }
    }
    if (all_scalar_const) {
        snode *n = sn_new(SN_ENUM);
        n->lits = calloc(alts->n, sizeof(char *));
        for (int i = 0; i < alts->n; i++) {
            sbuf lit = {0};
            jv_dump(jv_get(alts->items[i], "const"), &lit);
            n->lits[i] = lit.s;
            n->n_lits++;
        }
        return n;
    }

    snode *n = sn_new(SN_UNION);
    n->alts = calloc(alts->n, sizeof(snode *));
    for (int i = 0; i < alts->n; i++) {
        n->alts[n->n_alts] = compile_node(alts->items[i], err, errcap, depth + 1);
        if (!n->alts[n->n_alts]) { schema_free(n); return NULL; }
        n->n_alts++;
    }
    return n;
}

static snode *compile_node(jv *s, char *err, int errcap, int depth) {
    if (depth > 24) { snprintf(err, errcap, "schema too deep"); return NULL; }
    if (!s || s->type == J_NULL || (s->type == J_OBJ && s->n == 0) ||
        s->type == J_BOOL) // `true` / `{}` = anything
        return sn_new(SN_ANY);
    if (s->type != J_OBJ) { snprintf(err, errcap, "schema node must be an object"); return NULL; }

    jv *one = jv_get(s, "oneOf");
    jv *any = jv_get(s, "anyOf");
    if (one || any) return compile_oneof(one ? one : any, err, errcap, depth);

    // enum / const dominate the type
    jv *en = jv_get(s, "enum");
    jv *cn = jv_get(s, "const");
    if (en || cn) {
        snode *n = sn_new(SN_ENUM);
        int cnt = en ? en->n : 1;
        n->lits = calloc(cnt, sizeof(char *));
        for (int i = 0; i < cnt; i++) {
            jv *v = en ? en->items[i] : cn;
            if (v->type != J_STR && v->type != J_NUM &&
                v->type != J_BOOL && v->type != J_NULL) {
                snprintf(err, errcap, "enum values must be scalars");
                schema_free(n);
                return NULL;
            }
            sbuf lit = {0};
            jv_dump(v, &lit);
            n->lits[i] = lit.s;
            n->n_lits++;
        }
        if (n->n_lits == 0 || n->n_lits > 60) {
            snprintf(err, errcap, "enum size must be 1..60");
            schema_free(n);
            return NULL;
        }
        return n;
    }

    jv *ty = jv_get(s, "type");
    if (!ty) {
        if (jv_get(s, "properties")) return compile_typed(s, "object", err, errcap, depth);
        if (jv_get(s, "items"))      return compile_typed(s, "array", err, errcap, depth);
        return sn_new(SN_ANY);
    }
    if (ty->type == J_STR) return compile_typed(s, ty->str, err, errcap, depth);
    if (ty->type == J_ARR) { // union, e.g. ["string","null"]
        snode *n = sn_new(SN_UNION);
        n->alts = calloc(ty->n, sizeof(snode *));
        bool has_num = false;
        for (int i = 0; i < ty->n; i++) {
            const char *t = jv_str(ty->items[i], "?");
            if ((!strcmp(t, "number") || !strcmp(t, "integer"))) {
                if (has_num) continue; // merge number|integer
                has_num = true;
                t = strcmp(t, "integer") == 0 && ty->n == 1 ? "integer" : "number";
            }
            snode *alt = compile_typed(s, t, err, errcap, depth + 1);
            if (!alt) { schema_free(n); return NULL; }
            n->alts[n->n_alts++] = alt;
        }
        return n;
    }
    snprintf(err, errcap, "bad 'type' value");
    return NULL;
}

snode *schema_compile(struct jv *schema, char *err, int errcap) {
    err[0] = 0;
    return compile_node(schema, err, errcap, 0);
}

// ---------------------------------------------------------------- validate

// frame phases
enum {
    P_START,          // value not begun
    P_OBJ_KEY1,       // after '{': key or '}'
    P_OBJ_KEY,        // after ',': key
    P_OBJ_INKEY,      // inside key string
    P_OBJ_COLON,
    P_OBJ_NEXT,       // after value: ',' or '}'
    P_ARR_FIRST,      // after '[': value or ']'
    P_ARR_NEXT,       // after item: ',' or ']'
    P_STR,            // inside string
    P_LIT,            // enum / bool / null literal
    P_NUM,
};

// number micro-states (frame->sub)
enum { N_START, N_MINUS, N_ZERO, N_INT, N_FRAC0, N_FRAC, N_EXP0, N_EXP1, N_EXP };

static bool is_ws(uint8_t c) {
    return c == ' ' || c == '\t' || c == '\n' || c == '\r';
}

void sval_init(sval *v, const snode *root) {
    memset(v, 0, sizeof(*v));
    v->stack[0] = (sframe){ .node = root, .phase = P_START };
    v->depth = 1;
}

// key candidates from prop index `from`: every prop until (and including)
// the first required one may come next
static uint64_t key_candidates(const snode *n, int from) {
    uint64_t m = 0;
    for (int i = from; i < n->n_props; i++) {
        m |= 1ull << i;
        if (n->req[i]) break;
    }
    return m;
}

static bool close_allowed(const snode *n, int from) {
    for (int i = from; i < n->n_props; i++)
        if (n->req[i]) return false;
    return true;
}

static void frame_done(sval *v);

// child value finished: advance parent
static void frame_done(sval *v) {
    v->depth--;
    if (v->depth == 0) { v->done = true; return; }
    sframe *f = &v->stack[v->depth - 1];
    if (f->node->kind == SN_OBJ) f->phase = P_OBJ_NEXT;
    else                         f->phase = P_ARR_NEXT; // SN_ARR
}

// begin a value of type `n` on top of the stack (replaces union in place)
static bool push_value(sval *v, const snode *n) {
    if (v->depth >= (int)(sizeof(v->stack) / sizeof(v->stack[0]))) return false;
    v->stack[v->depth++] = (sframe){ .node = n, .phase = P_START };
    return true;
}

// which union alternative starts with byte c?
static const snode *pick_alt(const snode *u, uint8_t c) {
    for (int i = 0; i < u->n_alts; i++) {
        const snode *a = u->alts[i];
        switch (a->kind) {
            case SN_STR:  if (c == '"') return a; break;
            case SN_ENUM: if (c == a->lits[0][0]) return a; break; // usually strings
            case SN_OBJ:  if (c == '{') return a; break;
            case SN_ARR:  if (c == '[') return a; break;
            case SN_BOOL: if (c == 't' || c == 'f') return a; break;
            case SN_NULL: if (c == 'n') return a; break;
            case SN_NUM: case SN_INT:
                if (c == '-' || (c >= '0' && c <= '9')) return a;
                break;
            case SN_ANY:  return a;
            default: break;
        }
    }
    return NULL;
}

// string content byte (frame->sub tracks escapes); returns -1 invalid,
// 0 continue, 1 string closed
static int str_byte(uint8_t c, uint8_t *sub) {
    if (*sub == 1) { // after backslash
        if (c == '"' || c == '\\' || c == '/' || c == 'b' || c == 'f' ||
            c == 'n' || c == 'r' || c == 't') { *sub = 0; return 0; }
        if (c == 'u') { *sub = 2; return 0; }
        return -1;
    }
    if (*sub >= 2) { // \uXXXX
        if ((c >= '0' && c <= '9') || (c >= 'a' && c <= 'f') ||
            (c >= 'A' && c <= 'F')) {
            *sub = *sub == 5 ? 0 : *sub + 1;
            return 0;
        }
        return -1;
    }
    if (c == '"') return 1;
    if (c == '\\') { *sub = 1; return 0; }
    return c >= 0x20 ? 0 : -1;
}

// number byte; returns -1 invalid, 0 consumed, 1 complete-and-reconsume
static int num_byte(uint8_t c, uint8_t *st, bool integer) {
    switch (*st) {
        case N_START:
            if (c == '-') { *st = N_MINUS; return 0; }
            if (c == '0') { *st = N_ZERO; return 0; }
            if (c >= '1' && c <= '9') { *st = N_INT; return 0; }
            return -1;
        case N_MINUS:
            if (c == '0') { *st = N_ZERO; return 0; }
            if (c >= '1' && c <= '9') { *st = N_INT; return 0; }
            return -1;
        case N_ZERO:
        case N_INT:
            if (*st == N_INT && c >= '0' && c <= '9') return 0;
            if (!integer && c == '.') { *st = N_FRAC0; return 0; }
            if (!integer && (c == 'e' || c == 'E')) { *st = N_EXP0; return 0; }
            return 1;
        case N_FRAC0:
            if (c >= '0' && c <= '9') { *st = N_FRAC; return 0; }
            return -1;
        case N_FRAC:
            if (c >= '0' && c <= '9') return 0;
            if (c == 'e' || c == 'E') { *st = N_EXP0; return 0; }
            return 1;
        case N_EXP0:
            if (c == '+' || c == '-') { *st = N_EXP1; return 0; }
            if (c >= '0' && c <= '9') { *st = N_EXP; return 0; }
            return -1;
        case N_EXP1:
            if (c >= '0' && c <= '9') { *st = N_EXP; return 0; }
            return -1;
        case N_EXP:
            if (c >= '0' && c <= '9') return 0;
            return 1;
    }
    return -1;
}

static bool num_complete(uint8_t st) {
    return st == N_ZERO || st == N_INT || st == N_FRAC || st == N_EXP;
}

// feed one byte; returns -1 invalid, 0 consumed, 1 reconsume (frame popped)
static int feed_byte(sval *v, uint8_t c) {
    if (v->done) return -1; // nothing after the root value
    sframe *f = &v->stack[v->depth - 1];
    const snode *n = f->node;

    // generic any-value subtree
    if (n->kind == SN_ANY) {
        if (f->phase == P_START) {
            if (is_ws(c)) return 0;
            if (n->min_items) jsonv_init(&v->any);      // object-rooted
            else              jsonv_init_any(&v->any);  // any value
            f->phase = P_STR; // "running"
        }
        if (v->any.done) { frame_done(v); return 1; }
        if (jsonv_feed(&v->any, (const char *)&c, 1)) {
            if (v->any.done) frame_done(v);
            return 0;
        }
        // invalid for the submachine: if it stopped at a self-terminating
        // value end (number at top level), the byte belongs to our parent
        if (jsonv_value_end(&v->any)) { frame_done(v); return 1; }
        return -1;
    }

    switch (f->phase) {
    case P_START:
        if (is_ws(c)) return 0;
        switch (n->kind) {
        case SN_UNION: {
            const snode *alt = pick_alt(n, c);
            if (!alt) return -1;
            v->stack[v->depth - 1].node = alt; // resolve in place
            return feed_byte(v, c);
        }
        case SN_STR:
            if (c != '"') return -1;
            f->phase = P_STR; f->sub = 0;
            return 0;
        case SN_ENUM:
        case SN_BOOL:
        case SN_NULL:
            f->phase = P_LIT;
            f->lit_pos = 0;
            if (n->kind == SN_ENUM) {
                f->alive = (n->n_lits >= 64 ? ~0ull : (1ull << n->n_lits) - 1);
            } else {
                f->alive = n->kind == SN_BOOL ? 3 : 1; // true/false or null
            }
            return feed_byte(v, c) == -1 ? -1 : 0;
        case SN_NUM:
        case SN_INT:
            f->phase = P_NUM; f->sub = N_START;
            return num_byte(c, &f->sub, n->kind == SN_INT) == 0 ? 0 : -1;
        case SN_OBJ:
            if (c != '{') return -1;
            f->phase = P_OBJ_KEY1; f->idx = 0;
            return 0;
        case SN_ARR:
            if (c != '[') return -1;
            f->phase = P_ARR_FIRST; f->idx = 0;
            return 0;
        default:
            return -1;
        }

    case P_STR: {
        int r = str_byte(c, &f->sub);
        if (r < 0) return -1;
        if (r == 1) frame_done(v);
        return 0;
    }

    case P_LIT: {
        // match against alive literal candidates
        static const char *bools[] = { "true", "false" };
        static const char *nulls[] = { "null" };
        const char *const *lits = n->kind == SN_ENUM ? (const char *const *)n->lits :
                                  n->kind == SN_BOOL ? bools : nulls;
        int cnt = n->kind == SN_ENUM ? n->n_lits : (n->kind == SN_BOOL ? 2 : 1);
        uint64_t next = 0;
        bool completed = false;
        for (int i = 0; i < cnt; i++) {
            if (!(f->alive & (1ull << i))) continue;
            const char *L = lits[i];
            if (L[f->lit_pos] != (char)c) continue;
            if (L[f->lit_pos + 1] == 0) completed = true;
            else next |= 1ull << i;
        }
        if (completed) { frame_done(v); return 0; }
        if (!next) return -1;
        f->alive = next;
        f->lit_pos++;
        return 0;
    }

    case P_NUM: {
        int r = num_byte(c, &f->sub, n->kind == SN_INT);
        if (r < 0) return -1;
        if (r == 1) { frame_done(v); return 1; }
        return 0;
    }

    case P_OBJ_KEY1:
    case P_OBJ_KEY:
        if (is_ws(c)) return 0;
        if (c == '}' && f->phase == P_OBJ_KEY1) {
            if (!close_allowed(n, f->idx)) return -1;
            frame_done(v);
            return 0;
        }
        if (c != '"') return -1;
        f->alive = key_candidates(n, f->idx);
        if (!f->alive) return -1;
        f->phase = P_OBJ_INKEY;
        f->lit_pos = 0;
        return 0;

    case P_OBJ_INKEY: {
        if (c == '"') {
            // exactly one candidate must match to full length
            for (int i = 0; i < n->n_props; i++) {
                if ((f->alive & (1ull << i)) && n->key_len[i] == f->lit_pos) {
                    f->idx = i + 1;
                    f->sub = i; // remember which prop for the value
                    f->phase = P_OBJ_COLON;
                    return 0;
                }
            }
            return -1;
        }
        uint64_t next = 0;
        for (int i = 0; i < n->n_props; i++)
            if ((f->alive & (1ull << i)) && f->lit_pos < n->key_len[i] &&
                n->keys[i][f->lit_pos] == (char)c)
                next |= 1ull << i;
        if (!next) return -1;
        f->alive = next;
        f->lit_pos++;
        return 0;
    }

    case P_OBJ_COLON:
        if (is_ws(c)) return 0;
        if (c != ':') return -1;
        f->phase = P_OBJ_NEXT; // resumed here after the child completes
        return push_value(v, n->props[f->sub]) ? 0 : -1;

    case P_OBJ_NEXT:
        if (is_ws(c)) return 0;
        if (c == ',') {
            if (f->idx >= n->n_props || !key_candidates(n, f->idx)) return -1;
            f->phase = P_OBJ_KEY;
            return 0;
        }
        if (c == '}') {
            if (!close_allowed(n, f->idx)) return -1;
            frame_done(v);
            return 0;
        }
        return -1;

    case P_ARR_FIRST:
        if (is_ws(c)) return 0;
        if (c == ']') {
            if (n->min_items > 0) return -1;
            frame_done(v);
            return 0;
        }
        f->idx = 1;
        f->phase = P_ARR_NEXT;
        if (!push_value(v, n->items)) return -1;
        return feed_byte(v, c);

    case P_ARR_NEXT:
        if (is_ws(c)) return 0;
        if (c == ',') {
            if (n->max_items >= 0 && f->idx >= n->max_items) return -1;
            f->idx++;
            return push_value(v, n->items) ? 0 : -1;
        }
        if (c == ']') {
            if (f->idx < n->min_items) return -1;
            frame_done(v);
            return 0;
        }
        return -1;
    }
    return -1;
}

bool sval_feed(sval *v, const char *s, int len) {
    for (int i = 0; i < len; i++) {
        int r = feed_byte(v, (uint8_t)s[i]);
        if (r < 0) return false;
        if (r == 1) { // reconsume in parent
            r = feed_byte(v, (uint8_t)s[i]);
            if (r < 0) return false;
            if (r == 1) return false; // double reconsume: shouldn't happen
        }
    }
    return true;
}

// ---------------------------------------------------------------- close

typedef struct { char *out; int cap, n; } emitq;

static void eq_put(emitq *q, const char *s) {
    while (*s && q->n < q->cap - 1) q->out[q->n++] = *s++;
}
static void eq_putc(emitq *q, char c) {
    if (q->n < q->cap - 1) q->out[q->n++] = c;
}

// minimal complete value for a schema node
static void emit_min(emitq *q, const snode *n, int depth) {
    if (depth > 24) { eq_put(q, "null"); return; }
    switch (n->kind) {
        case SN_ANY:  eq_put(q, n->min_items ? "{}" : "null"); break;
        case SN_NULL: eq_put(q, "null"); break;
        case SN_BOOL: eq_put(q, "false"); break;
        case SN_NUM: case SN_INT: eq_putc(q, '0'); break;
        case SN_STR:  eq_put(q, "\"\""); break;
        case SN_ENUM: eq_put(q, n->lits[0]); break;
        case SN_UNION: {
            for (int i = 0; i < n->n_alts; i++)
                if (n->alts[i]->kind == SN_NULL) { eq_put(q, "null"); return; }
            emit_min(q, n->alts[0], depth + 1);
            break;
        }
        case SN_ARR:
            eq_putc(q, '[');
            for (int i = 0; i < n->min_items; i++) {
                if (i) eq_putc(q, ',');
                emit_min(q, n->items, depth + 1);
            }
            eq_putc(q, ']');
            break;
        case SN_OBJ: {
            eq_putc(q, '{');
            bool first = true;
            for (int i = 0; i < n->n_props; i++) {
                if (!n->req[i]) continue;
                if (!first) eq_putc(q, ',');
                first = false;
                eq_putc(q, '"'); eq_put(q, n->keys[i]); eq_put(q, "\":");
                emit_min(q, n->props[i], depth + 1);
            }
            eq_putc(q, '}');
            break;
        }
    }
}

// emit the remaining required properties of an object frame and close it.
// need_comma: a ',' must precede the first emitted property.
// force_one: at least one property must be emitted (a ',' was already
// consumed, so a bare '}' would be invalid JSON).
static void close_obj(emitq *q, const snode *n, int from, bool need_comma,
                      bool force_one) {
    bool emitted = false;
    for (int i = from; i < n->n_props; i++) {
        if (!n->req[i]) continue;
        if (need_comma) eq_putc(q, ',');
        need_comma = true;
        emitted = true;
        eq_putc(q, '"'); eq_put(q, n->keys[i]); eq_put(q, "\":");
        emit_min(q, n->props[i], 0);
    }
    if (force_one && !emitted && from < n->n_props) {
        eq_putc(q, '"'); eq_put(q, n->keys[from]); eq_put(q, "\":");
        emit_min(q, n->props[from], 0);
    }
    eq_putc(q, '}');
}

int sval_close(sval *v, char *out, int cap) {
    emitq q = { out, cap, 0 };
    if (v->done) { out[0] = 0; return 0; }
    // nothing generated at all: emit a full minimal document
    if (v->depth == 1 && v->stack[0].phase == P_START &&
        v->stack[0].node->kind != SN_ANY) {
        emit_min(&q, v->stack[0].node, 0);
        out[q.n] = 0;
        return q.n;
    }
    while (v->depth > 0) {
        sframe *f = &v->stack[v->depth - 1];
        const snode *n = f->node;
        switch (n->kind == SN_ANY ? P_STR + 100 : f->phase) {
        case P_STR + 100: { // any-subtree: let the generic machine close
            if (f->phase == P_START) { emit_min(&q, n, 0); break; }
            char tmp[512];
            int cn = jsonv_close(&v->any, tmp, sizeof(tmp));
            if (cn > 0) eq_put(&q, tmp);
            else if (!v->any.done) eq_put(&q, n->min_items ? "{}" : "null");
            break;
        }
        case P_START:
            emit_min(&q, n, 0);
            break;
        case P_STR:
            if (f->sub == 1) eq_putc(&q, 'n');           // dangling backslash
            while (f->sub >= 2) { eq_putc(&q, '0');       // partial \uXXXX
                                  f->sub = f->sub == 5 ? 0 : f->sub + 1; }
            eq_putc(&q, '"');
            break;
        case P_LIT: {
            static const char *bools[] = { "true", "false" };
            static const char *nulls[] = { "null" };
            const char *const *lits = n->kind == SN_ENUM ? (const char *const *)n->lits :
                                      n->kind == SN_BOOL ? bools : nulls;
            int cnt = n->kind == SN_ENUM ? n->n_lits : (n->kind == SN_BOOL ? 2 : 1);
            for (int i = 0; i < cnt; i++)
                if (f->alive & (1ull << i)) { eq_put(&q, lits[i] + f->lit_pos); break; }
            break;
        }
        case P_NUM:
            if (!num_complete(f->sub)) eq_putc(&q, '0');
            break;
        case P_OBJ_KEY1:
            close_obj(&q, n, f->idx, false, false);
            break;
        case P_OBJ_KEY: // a ',' was already consumed
            close_obj(&q, n, f->idx, false, true);
            break;
        case P_OBJ_INKEY: {
            // finish the lowest still-alive candidate key, give it a value
            for (int i = 0; i < n->n_props; i++) {
                if (!(f->alive & (1ull << i))) continue;
                eq_put(&q, n->keys[i] + f->lit_pos);
                eq_put(&q, "\":");
                emit_min(&q, n->props[i], 0);
                f->idx = i + 1;
                break;
            }
            close_obj(&q, n, f->idx, true, false);
            break;
        }
        case P_OBJ_COLON:
            eq_putc(&q, ':');
            emit_min(&q, n->props[f->sub], 0);
            close_obj(&q, n, f->idx, true, false);
            break;
        case P_OBJ_NEXT: // a value just completed, comma needed before more
            close_obj(&q, n, f->idx, true, false);
            break;
        case P_ARR_FIRST:
        case P_ARR_NEXT:
            for (int i = f->idx; i < n->min_items; i++) {
                if (i > 0 || f->phase == P_ARR_NEXT) eq_putc(&q, ',');
                emit_min(&q, n->items, 0);
            }
            eq_putc(&q, ']');
            break;
        }
        v->depth--;
    }
    v->done = true;
    out[q.n] = 0;
    return q.n;
}
